/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface CRAppLocator : NSObject {

	NSString* _apiURL;
	NSString* _apmURL;
	NSString* _appLoadURL;
	NSString* _txnURL;

}

@property (nonatomic,copy,readonly) NSString * apiURL;                  //@synthesize apiURL=_apiURL - In the implementation block
@property (nonatomic,copy,readonly) NSString * apmURL;                  //@synthesize apmURL=_apmURL - In the implementation block
@property (nonatomic,copy,readonly) NSString * appLoadURL;              //@synthesize appLoadURL=_appLoadURL - In the implementation block
@property (nonatomic,copy,readonly) NSString * txnURL;                  //@synthesize txnURL=_txnURL - In the implementation block
-(NSString *)txnURL;
-(id)initWithAppId:(id)arg1 ;
-(id)getDomainFromAppId:(id)arg1 ;
-(NSString *)apiURL;
-(NSString *)apmURL;
-(NSString *)appLoadURL;
@end

