/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSNumber, NSString;

@interface CRAppInfo : NSObject {

	BOOL _hasAlternateVersion;
	NSNumber* _isPirated;
	NSString* _bundleVersion;
	NSString* _marketingVersion;
	NSString* _bundleIdentifier;
	NSString* _alternateVersion;

}

@property (readonly) NSNumber * isPirated;                     //@synthesize isPirated=_isPirated - In the implementation block
@property (readonly) NSString * bundleVersion;                 //@synthesize bundleVersion=_bundleVersion - In the implementation block
@property (readonly) NSString * marketingVersion;              //@synthesize marketingVersion=_marketingVersion - In the implementation block
@property (readonly) NSString * bundleIdentifier;              //@synthesize bundleIdentifier=_bundleIdentifier - In the implementation block
@property (readonly) BOOL hasAlternateVersion;                 //@synthesize hasAlternateVersion=_hasAlternateVersion - In the implementation block
@property (retain) NSString * alternateVersion;                //@synthesize alternateVersion=_alternateVersion - In the implementation block
+(id)appInfo;
-(NSNumber *)isPirated;
-(BOOL)hasAlternateVersion;
-(NSString *)alternateVersion;
-(NSString *)marketingVersion;
-(void)setAlternateVersion:(NSString *)arg1 ;
-(id)init;
-(NSString *)bundleIdentifier;
-(NSString *)bundleVersion;
-(id)appVersion;
@end

