/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray, CRDirectoryTree, NSString, NSFileHandle;

@interface CRBreadcrumbsArchive : NSObject {

	unsigned _maxCount;
	NSMutableArray* _breadcrumbs;
	NSMutableArray* _reservedBreadcrumbs;
	CRDirectoryTree* _directoryTree;
	NSString* _nameDirectory;
	NSFileHandle* _fileHandle;
	NSFileHandle* _reservedFileHandle;
	NSString* _path0;
	NSString* _path1;
	NSString* _pathToReservedBreadcrumbs;
	unsigned long long _breadcrumbCount;
	unsigned long long _countOnActiveFile;

}

@property (nonatomic,retain) NSMutableArray * breadcrumbs;                        //@synthesize breadcrumbs=_breadcrumbs - In the implementation block
@property (nonatomic,retain) NSMutableArray * reservedBreadcrumbs;                //@synthesize reservedBreadcrumbs=_reservedBreadcrumbs - In the implementation block
@property (assign,nonatomic,__weak) CRDirectoryTree * directoryTree;              //@synthesize directoryTree=_directoryTree - In the implementation block
@property (nonatomic,copy) NSString * nameDirectory;                              //@synthesize nameDirectory=_nameDirectory - In the implementation block
@property (retain) NSFileHandle * fileHandle;                                     //@synthesize fileHandle=_fileHandle - In the implementation block
@property (retain) NSFileHandle * reservedFileHandle;                             //@synthesize reservedFileHandle=_reservedFileHandle - In the implementation block
@property (nonatomic,copy) NSString * path0;                                      //@synthesize path0=_path0 - In the implementation block
@property (nonatomic,copy) NSString * path1;                                      //@synthesize path1=_path1 - In the implementation block
@property (nonatomic,copy) NSString * pathToReservedBreadcrumbs;                  //@synthesize pathToReservedBreadcrumbs=_pathToReservedBreadcrumbs - In the implementation block
@property (assign,nonatomic) unsigned maxCount;                                   //@synthesize maxCount=_maxCount - In the implementation block
@property (assign,nonatomic) unsigned long long breadcrumbCount;                  //@synthesize breadcrumbCount=_breadcrumbCount - In the implementation block
@property (assign,nonatomic) unsigned long long countOnActiveFile;                //@synthesize countOnActiveFile=_countOnActiveFile - In the implementation block
+(id)convertArrayToUserBreadcrumbFormat:(id)arg1 ;
-(CRDirectoryTree *)directoryTree;
-(void)setDirectoryTree:(CRDirectoryTree *)arg1 ;
-(id)readBreadcrumbs;
-(void)saveBreadcrumbs;
-(void)addBreadcrumbShuffleFiles;
-(void)addBreadcrumbOpenFile:(id)arg1 ;
-(void)addBreadcrumbToFile:(id)arg1 ;
-(void)addBreadcrumbToArray:(id)arg1 ;
-(void)clearAndAddBreadcrumbToReservedFile:(id)arg1 ;
-(void)clearAndAddBreadcrumbToReservedArray:(id)arg1 ;
-(void)addBreadcrumb:(int)arg1 withObject:(id)arg2 withTimestamp:(id)arg3 ;
-(id)recentBreadcrumbs;
-(BOOL)isPlausibleBreadcrumb:(id)arg1 ;
-(void)clearBreadcrumbsOnDisk;
-(void)readBreadcrumbsFromFile:(id)arg1 intoArray:(id)arg2 ;
-(void)addSessionStartBreadcrumb;
-(void)addBreadcrumb:(int)arg1 withObject:(id)arg2 ;
-(id)extractRecentUserBreadcrumbs;
-(void)clearBreadcrumbs;
-(unsigned long long)path0FileSize;
-(unsigned long long)path1FileSize;
-(NSMutableArray *)breadcrumbs;
-(void)setBreadcrumbs:(NSMutableArray *)arg1 ;
-(NSMutableArray *)reservedBreadcrumbs;
-(void)setReservedBreadcrumbs:(NSMutableArray *)arg1 ;
-(NSString *)nameDirectory;
-(void)setNameDirectory:(NSString *)arg1 ;
-(NSFileHandle *)reservedFileHandle;
-(void)setReservedFileHandle:(NSFileHandle *)arg1 ;
-(NSString *)path0;
-(void)setPath0:(NSString *)arg1 ;
-(NSString *)path1;
-(void)setPath1:(NSString *)arg1 ;
-(NSString *)pathToReservedBreadcrumbs;
-(void)setPathToReservedBreadcrumbs:(NSString *)arg1 ;
-(unsigned long long)breadcrumbCount;
-(void)setBreadcrumbCount:(unsigned long long)arg1 ;
-(unsigned long long)countOnActiveFile;
-(void)setCountOnActiveFile:(unsigned long long)arg1 ;
-(void)setMaxCount:(unsigned)arg1 ;
-(id)initWithName:(id)arg1 maxCount:(unsigned)arg2 ;
-(NSFileHandle *)fileHandle;
-(void)setFileHandle:(NSFileHandle *)arg1 ;
-(unsigned)maxCount;
@end

