/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class CritterImpl, NSMutableData, NSURLResponse;

@interface CRConnectionHandler : NSObject {

	CritterImpl* _delegate;
	NSMutableData* _dataReceived;
	NSURLResponse* _response;

}

@property (readonly) CritterImpl * delegate;                  //@synthesize delegate=_delegate - In the implementation block
@property (retain) NSMutableData * dataReceived;              //@synthesize dataReceived=_dataReceived - In the implementation block
@property (retain) NSURLResponse * response;                  //@synthesize response=_response - In the implementation block
+(id)handlerWithDelegate:(id)arg1 ;
-(id)initWithCritterDelegate:(id)arg1 ;
-(void)handleResponse:(long long)arg1 andData:(id)arg2 ;
-(void)doSendRequest:(id)arg1 ;
-(BOOL)receivedErrorResponse;
-(id)dataReceivedAsString;
-(NSMutableData *)dataReceived;
-(void)setDataReceived:(NSMutableData *)arg1 ;
-(void)sendRequest:(id)arg1 ;
-(id)init;
-(CritterImpl *)delegate;
-(NSURLResponse *)response;
-(long long)statusCode;
-(void)connection:(id)arg1 didFailWithError:(id)arg2 ;
-(void)connection:(id)arg1 didReceiveData:(id)arg2 ;
-(void)connectionDidFinishLoading:(id)arg1 ;
-(void)connection:(id)arg1 didReceiveResponse:(id)arg2 ;
-(void)handleError:(id)arg1 ;
-(void)setResponse:(NSURLResponse *)arg1 ;
@end

