/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/CRPart.h>

@class NSData;

@interface CRDataPart : CRPart {

	NSData* _partData;

}

@property (retain) NSData * partData;              //@synthesize partData=_partData - In the implementation block
-(id)initWithName:(id)arg1 andFilename:(id)arg2 andData:(id)arg3 ;
-(void)setPartData:(NSData *)arg1 ;
-(NSData *)partData;
-(void)serializeTo:(id)arg1 ;
@end

