/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <pokemongo/pokemongo-Structs.h>
@class NSString;

@interface CRDetectedClass : NSObject {

	BOOL _isNSObjectSubclass;
	BOOL _isWebViewSubclass;
	BOOL _isViewControllerSubclass;
	NSString* _name;

}

@property (nonatomic,readonly) NSString * name;                            //@synthesize name=_name - In the implementation block
@property (nonatomic,readonly) BOOL isNSObjectSubclass;                    //@synthesize isNSObjectSubclass=_isNSObjectSubclass - In the implementation block
@property (nonatomic,readonly) BOOL isWebViewSubclass;                     //@synthesize isWebViewSubclass=_isWebViewSubclass - In the implementation block
@property (nonatomic,readonly) BOOL isViewControllerSubclass;              //@synthesize isViewControllerSubclass=_isViewControllerSubclass - In the implementation block
+(id)detectedClassWithFoundClass:(const cr_found_class_t*)arg1 ;
-(id)initWithFoundClass:(const cr_found_class_t*)arg1 ;
-(Class)getClass;
-(BOOL)isNSObjectSubclass;
-(BOOL)isWebViewSubclass;
-(BOOL)isViewControllerSubclass;
-(NSString *)name;
@end

