/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/CRPart.h>

@class NSDictionary;

@interface CRJSONPart : CRPart {

	NSDictionary* _dataDict;

}

@property (retain) NSDictionary * dataDict;              //@synthesize dataDict=_dataDict - In the implementation block
-(id)initWithName:(id)arg1 andFilename:(id)arg2 andDict:(id)arg3 ;
-(NSDictionary *)dataDict;
-(void)setDataDict:(NSDictionary *)arg1 ;
-(void)serializeTo:(id)arg1 ;
@end

