/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/NSProxy.h>

@class NSURLSessionTask, CRNetStatDispatch, CRRequestState;

@interface CRNSURLSessionTaskProxy : NSProxy {

	NSURLSessionTask* _taskDelegate;
	CRNetStatDispatch* _dispatch;
	CRRequestState* _reqState;
	unsigned long long _resumeDataSize;

}

@property (nonatomic,readonly) NSURLSessionTask * taskDelegate;              //@synthesize taskDelegate=_taskDelegate - In the implementation block
@property (nonatomic,readonly) CRNetStatDispatch * dispatch;                 //@synthesize dispatch=_dispatch - In the implementation block
@property (nonatomic,retain) CRRequestState * reqState;                      //@synthesize reqState=_reqState - In the implementation block
@property (assign,nonatomic) unsigned long long resumeDataSize;              //@synthesize resumeDataSize=_resumeDataSize - In the implementation block
-(void)responseFinishedWithError:(id)arg1 ;
-(void)receivedBytes:(unsigned long long)arg1 ;
-(void)receivedResponse:(id)arg1 ;
-(void)finishedDownloadingToURL:(id)arg1 ;
-(id)initDataTaskWithSession:(id)arg1 URL:(id)arg2 completionHandler:(/*^block*/id)arg3 dispatch:(id)arg4 ;
-(id)initDataTaskWithSession:(id)arg1 request:(id)arg2 completionHandler:(/*^block*/id)arg3 dispatch:(id)arg4 ;
-(id)initDownloadTaskWithSession:(id)arg1 request:(id)arg2 completionHandler:(/*^block*/id)arg3 dispatch:(id)arg4 ;
-(id)initDownloadTaskWithSession:(id)arg1 url:(id)arg2 completionHandler:(/*^block*/id)arg3 dispatch:(id)arg4 ;
-(id)initDownloadTaskWithSession:(id)arg1 resumeData:(id)arg2 completionHandler:(/*^block*/id)arg3 dispatch:(id)arg4 ;
-(void)setReqState:(CRRequestState *)arg1 ;
-(CRRequestState *)reqState;
-(/*^block*/id)wrapDataCompletionHandler:(/*^block*/id)arg1 forSession:(id)arg2 ;
-(id)initWithTaskDelegate:(id)arg1 dispatch:(id)arg2 ;
-(/*^block*/id)wrapDownloadCompletionHandler:(/*^block*/id)arg1 forSession:(id)arg2 ;
-(void)setResumeDataSize:(unsigned long long)arg1 ;
-(NSURLSessionTask *)taskDelegate;
-(unsigned long long)resumeDataSize;
-(void)cancel;
-(BOOL)respondsToSelector:(SEL)arg1 ;
-(id)description;
-(id)debugDescription;
-(id)methodSignatureForSelector:(SEL)arg1 ;
-(void)suspend;
-(void)forwardInvocation:(id)arg1 ;
-(void)resume;
-(CRNetStatDispatch *)dispatch;
@end

