/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/NSProxy.h>
#import <libobjc.A.dylib/NSURLConnectionDelegate.h>
#import <libobjc.A.dylib/NSURLConnectionDataDelegate.h>

@class CRNetStatDispatch, CRRequestState, NSString;

@interface CRNSURLConnectionDelegateProxy : NSProxy <NSURLConnectionDelegate, NSURLConnectionDataDelegate> {

	id _delegate;
	CRNetStatDispatch* _dispatch;
	CRRequestState* _reqState;

}

@property (nonatomic,retain) id delegate;                               //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) CRNetStatDispatch * dispatch;              //@synthesize dispatch=_dispatch - In the implementation block
@property (nonatomic,retain) CRRequestState * reqState;                 //@synthesize reqState=_reqState - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)isInstrumented;
+(void)uninstrumentNSURLConnection;
+(void)instrumentNSURLConnectionWithDispatch:(id)arg1 ;
-(void)setReqState:(CRRequestState *)arg1 ;
-(void)logStats;
-(id)initWithDelegate:(id)arg1 andStatsDispatch:(id)arg2 ;
-(void)addAssociationToConnection:(id)arg1 ;
-(void)startRequest:(id)arg1 ;
-(void)setDispatch:(CRNetStatDispatch *)arg1 ;
-(CRRequestState *)reqState;
-(void)connectionDidFinishDownloading:(id)arg1 destinationURL:(id)arg2 ;
-(void)connectionDidResumeDownloading:(id)arg1 totalBytesWritten:(long long)arg2 expectedTotalBytes:(long long)arg3 ;
-(void)connection:(id)arg1 didWriteData:(long long)arg2 totalBytesWritten:(long long)arg3 expectedTotalBytes:(long long)arg4 ;
-(void)setDelegate:(id)arg1 ;
-(BOOL)respondsToSelector:(SEL)arg1 ;
-(id)delegate;
-(id)methodSignatureForSelector:(SEL)arg1 ;
-(void)forwardInvocation:(id)arg1 ;
-(void)connection:(id)arg1 didFailWithError:(id)arg2 ;
-(void)connection:(id)arg1 didReceiveData:(id)arg2 ;
-(void)connectionDidFinishLoading:(id)arg1 ;
-(void)connection:(id)arg1 didReceiveResponse:(id)arg2 ;
-(void)connection:(id)arg1 didCancelAuthenticationChallenge:(id)arg2 ;
-(BOOL)connectionShouldUseCredentialStorage:(id)arg1 ;
-(void)connection:(id)arg1 willSendRequestForAuthenticationChallenge:(id)arg2 ;
-(BOOL)connection:(id)arg1 canAuthenticateAgainstProtectionSpace:(id)arg2 ;
-(id)connection:(id)arg1 needNewBodyStream:(id)arg2 ;
-(void)connection:(id)arg1 didSendBodyData:(long long)arg2 totalBytesWritten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4 ;
-(id)connection:(id)arg1 willCacheResponse:(id)arg2 ;
-(id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3 ;
-(CRNetStatDispatch *)dispatch;
@end

