/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/NSProxy.h>

@class NSURLSession, CRNetStatDispatch;

@interface CRNSURLSessionProxy : NSProxy {

	NSURLSession* _session;
	CRNetStatDispatch* _dispatch;

}

@property (nonatomic,readonly) NSURLSession * session;                    //@synthesize session=_session - In the implementation block
@property (nonatomic,readonly) CRNetStatDispatch * dispatch;              //@synthesize dispatch=_dispatch - In the implementation block
+(BOOL)isInstrumented;
+(void)instrumentNSURLSessionWithDispatch:(id)arg1 ;
+(void)uninstrumentNSURLSession;
-(id)initWithSession:(id)arg1 dispatch:(id)arg2 ;
-(id)dataTaskWithURL:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(id)downloadTaskWithRequest:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(id)dataTaskWithURL:(id)arg1 ;
-(id)downloadTaskWithResumeData:(id)arg1 ;
-(id)downloadTaskWithURL:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(id)downloadTaskWithResumeData:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(id)dataTaskWithRequest:(id)arg1 ;
-(NSURLSession *)session;
-(BOOL)respondsToSelector:(SEL)arg1 ;
-(id)description;
-(id)debugDescription;
-(id)methodSignatureForSelector:(SEL)arg1 ;
-(void)forwardInvocation:(id)arg1 ;
-(id)dataTaskWithRequest:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
-(id)downloadTaskWithURL:(id)arg1 ;
-(id)downloadTaskWithRequest:(id)arg1 ;
-(CRNetStatDispatch *)dispatch;
@end

