/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface CRPluginException : NSObject {

	int _crExceptionType;
	NSString* _name;
	NSString* _reason;
	NSString* _platform;
	NSString* _subplatform;
	NSString* _stacktrace;

}

@property (nonatomic,readonly) NSString * name;                     //@synthesize name=_name - In the implementation block
@property (nonatomic,readonly) NSString * reason;                   //@synthesize reason=_reason - In the implementation block
@property (nonatomic,readonly) NSString * platform;                 //@synthesize platform=_platform - In the implementation block
@property (nonatomic,readonly) NSString * subplatform;              //@synthesize subplatform=_subplatform - In the implementation block
@property (nonatomic,readonly) int crExceptionType;                 //@synthesize crExceptionType=_crExceptionType - In the implementation block
@property (nonatomic,retain) NSString * stacktrace;                 //@synthesize stacktrace=_stacktrace - In the implementation block
-(id)initWithName:(id)arg1 reason:(id)arg2 stacktrace:(id)arg3 exceptionType:(int)arg4 platformId:(int)arg5 ;
-(id)stackframes;
-(NSString *)subplatform;
-(int)crExceptionType;
-(NSString *)stacktrace;
-(void)setStacktrace:(NSString *)arg1 ;
-(NSString *)name;
-(NSString *)reason;
-(NSString *)platform;
@end

