/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface CRPreferences : NSObject {

	NSString* _critterKey;

}

@property (nonatomic,retain) NSString * critterKey;              //@synthesize critterKey=_critterKey - In the implementation block
-(id)getValueWithKey:(id)arg1 andDictionaryName:(id)arg2 ;
-(void)storeValue:(id)arg1 forKey:(id)arg2 forDictionary:(id)arg3 ;
-(id)getRootDict;
-(void)doStoreValue:(id)arg1 forKey:(id)arg2 forDictionary:(id)arg3 wasWritten:(BOOL*)arg4 ;
-(void)storeValue:(id)arg1 forKey:(id)arg2 forDictionary:(id)arg3 wasWritten:(BOOL*)arg4 ;
-(id)initWithAppId:(id)arg1 ;
-(void)clearValueForKey:(id)arg1 andDictionary:(id)arg2 ;
-(NSString *)critterKey;
-(void)setCritterKey:(NSString *)arg1 ;
-(id)describe;
-(void)reset;
-(id)getDict:(id)arg1 ;
@end

