/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <pokemongo/pokemongo-Structs.h>
@class NSString;

@interface CRReachability : NSObject {

	BOOL localWiFiRef;
	BOOL _scheduled;
	SCNetworkReachabilityRef _reachabilityRef;
	NSString* _notificationCenterKey;

}

@property (retain) NSString * notificationCenterKey;              //@synthesize notificationCenterKey=_notificationCenterKey - In the implementation block
+(id)reachabilityForHostName:(id)arg1 withNotificationKey:(id)arg2 ;
+(id)reachabilityWithAddress:(const sockaddr_in*)arg1 withKey:(id)arg2 ;
+(id)reachabilityForWiFiWithNotificationKey:(id)arg1 ;
+(id)reachabilityForHostName:(id)arg1 ;
+(id)reachabilityForWiFi;
+(id)reachabilityForInternetConnection;
-(id)initWithNotificationKey:(id)arg1 ;
-(void)setNotificationCenterKey:(NSString *)arg1 ;
-(id)currentReachabilityStatusString;
-(NSString *)notificationCenterKey;
-(void)dealloc;
-(BOOL)connectionRequired;
-(int)currentReachabilityStatus;
-(BOOL)startNotifier;
-(void)stopNotifier;
@end

