/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray;

@interface CRTest : NSObject {

	BOOL _testing;
	NSMutableArray* _requests;

}

@property (assign,nonatomic) BOOL testing;                           //@synthesize testing=_testing - In the implementation block
@property (nonatomic,retain) NSMutableArray * requests;              //@synthesize requests=_requests - In the implementation block
+(BOOL)testing;
+(id)findRequest:(id)arg1 ;
+(void)sendRequest:(id)arg1 ;
+(void)tearDown;
+(id)sharedInstance;
+(void)setUp;
+(id)requests;
-(BOOL)testing;
-(NSMutableArray *)requests;
-(void)setRequests:(NSMutableArray *)arg1 ;
-(void)setTesting:(BOOL)arg1 ;
@end

