/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSDate;

@interface CRThrottle : NSObject {

	unsigned long long _maxTokens;
	double _timeWindow;
	double _tokensAccumulated;
	NSDate* _lastEventTime;

}

@property (assign,nonatomic) unsigned long long maxTokens;              //@synthesize maxTokens=_maxTokens - In the implementation block
@property (assign,nonatomic) double timeWindow;                         //@synthesize timeWindow=_timeWindow - In the implementation block
@property (assign,nonatomic) double tokensAccumulated;                  //@synthesize tokensAccumulated=_tokensAccumulated - In the implementation block
@property (nonatomic,retain) NSDate * lastEventTime;                    //@synthesize lastEventTime=_lastEventTime - In the implementation block
-(id)initWithMaxEvents:(unsigned long long)arg1 perUnitTime:(double)arg2 ;
-(BOOL)tryEvent;
-(unsigned long long)maxTokens;
-(void)setMaxTokens:(unsigned long long)arg1 ;
-(double)timeWindow;
-(void)setTimeWindow:(double)arg1 ;
-(double)tokensAccumulated;
-(void)setTokensAccumulated:(double)arg1 ;
-(NSDate *)lastEventTime;
-(void)setLastEventTime:(NSDate *)arg1 ;
@end

