/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/NSProxy.h>
#import <pokemongo/WCSessionDelegate.h>

@class NSSet, CRRequestState, CRNetStatDispatch, NSString;

@interface CRWCSessionDelegateProxy : NSProxy <WCSessionDelegate> {

	id _delegate;
	NSSet* _selectorsWeRespondTo;
	CRRequestState* _reqState;
	CRNetStatDispatch* _dispatch;

}

@property (assign,nonatomic) id delegate;                               //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) NSSet * selectorsWeRespondTo;              //@synthesize selectorsWeRespondTo=_selectorsWeRespondTo - In the implementation block
@property (nonatomic,retain) CRRequestState * reqState;                 //@synthesize reqState=_reqState - In the implementation block
@property (nonatomic,retain) CRNetStatDispatch * dispatch;              //@synthesize dispatch=_dispatch - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(BOOL)isInstrumented;
+(void)instrumentWCSessionWithDispatch:(id)arg1 ;
+(id)delegateForWCSession:(id)arg1 dispatch:(id)arg2 ;
+(void)replaceWCSessionmethod:(SEL)arg1 withSwizzledSelector:(SEL)arg2 implementedBlock:(id)arg3 ;
+(void)setDelegateForWCSession:(id)arg1 delegate:(id)arg2 dispatch:(id)arg3 ;
+(void)activateSessionForWCSession:(id)arg1 dispatch:(id)arg2 ;
+(void)sendMessageForWCSession:(id)arg1 message:(id)arg2 replyHandler:(/*^block*/id)arg3 errorHandler:(/*^block*/id)arg4 dispatch:(id)arg5 ;
+(void)sendMessageDataForWCSession:(id)arg1 data:(id)arg2 replyHandler:(/*^block*/id)arg3 errorHandler:(/*^block*/id)arg4 dispatch:(id)arg5 ;
+(id)transferUserInfoForWCSession:(id)arg1 userInfo:(id)arg2 dispatch:(id)arg3 ;
+(id)transferFileForWCSession:(id)arg1 file:(id)arg2 metadata:(id)arg3 dispatch:(id)arg4 ;
+(void)swizzleWCSessionDelegateWithDispatch:(id)arg1 ;
+(void)swizzleWCSessionSetDelegateWithDispatch:(id)arg1 ;
+(void)swizzleWCSessionActivateSessionWithDispatch:(id)arg1 ;
+(void)swizzleWCSessionSendMessageWithDispatch:(id)arg1 ;
+(void)swizzleWCSessionSendMessageDataWithDispatch:(id)arg1 ;
+(void)swizzleWCSessionTransferUserInfoWithDispatch:(id)arg1 ;
+(void)swizzleWCSessionTransferFileWithDispatch:(id)arg1 ;
+(id)performSwizzledWCSessionDelegate:(id)arg1 ;
+(void)performSwizzledWCSessionSetDelegate:(id)arg1 withProxy:(id)arg2 ;
+(id)proxyFromSession:(id)arg1 dispatch:(id)arg2 ;
+(id)performSwizzledWCSessionActivateSession:(id)arg1 ;
+(id)performSwizzledWCSessionSendMessage:(id)arg1 message:(id)arg2 replyHandler:(/*^block*/id)arg3 errorHandler:(/*^block*/id)arg4 ;
+(id)performSwizzledWCSessionMessageData:(id)arg1 data:(id)arg2 replyHandler:(/*^block*/id)arg3 errorHandler:(/*^block*/id)arg4 ;
+(id)performSwizzledWCSessionTransferUserInfo:(id)arg1 userInfo:(id)arg2 ;
+(id)performSwizzledWCSessionTransferFile:(id)arg1 file:(id)arg2 metadata:(id)arg3 ;
+(void)uninstrumentWCSession;
+(BOOL)respondsToSelector:(SEL)arg1 ;
-(NSSet *)selectorsWeRespondTo;
-(void)setSelectorsWeRespondTo:(NSSet *)arg1 ;
-(id)initWithDelegate:(id)arg1 dispatch:(id)arg2 ;
-(void)setReqState:(CRRequestState *)arg1 ;
-(void)setDispatch:(CRNetStatDispatch *)arg1 ;
-(CRRequestState *)reqState;
-(void)addAssociationToSession:(id)arg1 ;
-(void)setDelegate:(id)arg1 ;
-(BOOL)respondsToSelector:(SEL)arg1 ;
-(NSString *)description;
-(NSString *)debugDescription;
-(id)delegate;
-(id)methodSignatureForSelector:(SEL)arg1 ;
-(void)forwardInvocation:(id)arg1 ;
-(void)session:(id)arg1 didReceiveMessage:(id)arg2 replyHandler:(/*^block*/id)arg3 ;
-(void)session:(id)arg1 didReceiveMessage:(id)arg2 ;
-(void)session:(id)arg1 didReceiveMessageData:(id)arg2 replyHandler:(/*^block*/id)arg3 ;
-(void)session:(id)arg1 didReceiveMessageData:(id)arg2 ;
-(void)session:(id)arg1 didReceiveApplicationContext:(id)arg2 ;
-(void)session:(id)arg1 didReceiveFile:(id)arg2 ;
-(void)session:(id)arg1 didFinishFileTransfer:(id)arg2 error:(id)arg3 ;
-(void)session:(id)arg1 didReceiveUserInfo:(id)arg2 ;
-(void)session:(id)arg1 didFinishUserInfoTransfer:(id)arg2 error:(id)arg3 ;
-(CRNetStatDispatch *)dispatch;
@end

