/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <pokemongo/pokemongo-Structs.h>
@class UIScreen, UIWindow, UIView;

@interface DisplayConnection : NSObject {

	BOOL _needRecreateSurface;
	CGSize _requestedRenderingSize;
	UIScreen* _screen;
	UIWindow* _window;
	UIView* _view;
	CGSize _screenSize;
	UnityDisplaySurfaceBase* _surface;
	UnityDisplaySurfaceGLES* surfaceGLES;
	UnityDisplaySurfaceMTL* surfaceMTL;

}

@property (nonatomic,readonly) UnityDisplaySurfaceGLES* surfaceGLES; 
@property (nonatomic,readonly) UnityDisplaySurfaceMTL* surfaceMTL; 
@property (nonatomic,copy,readonly) UIScreen * screen;                            //@synthesize screen=_screen - In the implementation block
@property (nonatomic,copy,readonly) UIWindow * window;                            //@synthesize window=_window - In the implementation block
@property (nonatomic,copy,readonly) UIView * view;                                //@synthesize view=_view - In the implementation block
@property (nonatomic,readonly) CGSize screenSize;                                 //@synthesize screenSize=_screenSize - In the implementation block
@property (nonatomic,readonly) UnityDisplaySurfaceBase* surface;                  //@synthesize surface=_surface - In the implementation block
-(void)initRendering;
-(void)createView:(BOOL)arg1 showRightAway:(BOOL)arg2 ;
-(void)createWithWindow:(id)arg1 andView:(id)arg2 ;
-(UnityDisplaySurfaceMTL*)surfaceMTL;
-(UnityDisplaySurfaceGLES*)surfaceGLES;
-(void)recreateSurface:(RenderingSurfaceParams)arg1 ;
-(void)createView:(BOOL)arg1 ;
-(void)shouldShowWindow:(BOOL)arg1 ;
-(void)requestRenderingResolution:(CGSize)arg1 ;
-(id)init:(id)arg1 ;
-(void)dealloc;
-(UIWindow *)window;
-(UIView *)view;
-(UIScreen *)screen;
-(void)present;
-(UnityDisplaySurfaceBase*)surface;
-(CGSize)screenSize;
@end

