/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSString;


@protocol GTMFetcherAuthorizationProtocol <NSObject>
@property (readonly) NSString * userEmail; 
@property (readonly) BOOL canAuthorize; 
@property (assign) BOOL shouldAuthorizeAllRequests; 
@property (__weak) id<GTMSessionFetcherServiceProtocol> fetcherService; 
@optional
-(BOOL)shouldAuthorizeAllRequests;
-(id<GTMSessionFetcherServiceProtocol>)fetcherService;
-(void)authorizeRequest:(id)arg1 completionHandler:(/*^block*/id)arg2;
-(BOOL)primeForRefresh;
-(BOOL)canAuthorize;
-(void)setShouldAuthorizeAllRequests:(BOOL)arg1;
-(void)setFetcherService:(id)arg1;

@required
-(void)stopAuthorization;
-(void)authorizeRequest:(id)arg1 delegate:(id)arg2 didFinishSelector:(SEL)arg3;
-(void)stopAuthorizationForRequest:(id)arg1;
-(BOOL)isAuthorizingRequest:(id)arg1;
-(BOOL)isAuthorizedRequest:(id)arg1;
-(NSString *)userEmail;

@end

