/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface GTMOAuth2Keychain : NSObject
+(id)defaultKeychain;
+(id)keychainQueryForService:(id)arg1 account:(id)arg2 ;
+(void)setDefaultKeychain:(id)arg1 ;
-(id)passwordForService:(id)arg1 account:(id)arg2 error:(id*)arg3 ;
-(BOOL)removePasswordForService:(id)arg1 account:(id)arg2 error:(id*)arg3 ;
-(BOOL)setPassword:(id)arg1 forService:(id)arg2 accessibility:(void*)arg3 account:(id)arg4 error:(id*)arg5 ;
-(id)keychainQueryForService:(id)arg1 account:(id)arg2 ;
-(id)keyForService:(id)arg1 account:(id)arg2 ;
@end

