/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableURLRequest, NSThread, NSError;

@interface GTMOAuth2AuthorizationArgs : NSObject {

	NSMutableURLRequest* request_;
	id delegate_;
	SEL sel_;
	id completionHandler_;
	NSThread* thread_;
	NSError* error_;

}

@property (retain) NSMutableURLRequest * request; 
@property (retain) id delegate; 
@property (assign) SEL selector; 
@property (copy) id completionHandler; 
@property (retain) NSThread * thread; 
@property (retain) NSError * error; 
+(id)argsWithRequest:(id)arg1 delegate:(id)arg2 selector:(SEL)arg3 completionHandler:(id)arg4 thread:(id)arg5 ;
-(NSError *)error;
-(void)setDelegate:(id)arg1 ;
-(void)dealloc;
-(id)delegate;
-(NSMutableURLRequest *)request;
-(void)setSelector:(SEL)arg1 ;
-(id)completionHandler;
-(void)setCompletionHandler:(id)arg1 ;
-(SEL)selector;
-(void)setThread:(NSThread *)arg1 ;
-(NSThread *)thread;
-(void)setRequest:(NSMutableURLRequest *)arg1 ;
-(void)setError:(NSError *)arg1 ;
@end

