/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewController.h>

@class NSArray;

@interface GTMSessionFetcherLogViewController : UITableViewController {

	NSArray* logsFolderURLs_;
	BOOL opensScrolledToEnd_;
	/*^block*/id callbackBlock_;

}

@property (nonatomic,copy) id callbackBlock; 
+(id)controllerWithTarget:(id)arg1 selector:(SEL)arg2 ;
-(id)shortenedNameForURL:(id)arg1 ;
-(void)setCallbackBlock:(id)arg1 ;
-(id)callbackBlock;
-(void)setOpensScrolledToEnd:(BOOL)arg1 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(id)initWithStyle:(long long)arg1 ;
-(void)viewDidLoad;
-(void)doneButtonClicked:(id)arg1 ;
@end

