/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/GTMSessionFetcher.h>

@protocol OS_dispatch_queue;
@class GTMSessionFetcher, NSObject, NSURL, NSData, NSFileHandle, NSString, NSDictionary, NSURLRequest;

@interface GTMSessionUploadFetcher : GTMSessionFetcher {

	GTMSessionFetcher* _chunkFetcher;
	/*^block*/id _delegateCompletionHandler;
	NSObject*<OS_dispatch_queue> _delegateCallbackQueue;
	long long _initialBodyLength;
	long long _initialBodySent;
	NSURL* _uploadLocationURL;
	NSData* _uploadData;
	NSFileHandle* _uploadFileHandle;
	/*^block*/id _uploadDataProvider;
	long long _uploadFileLength;
	NSString* _uploadMIMEType;
	long long _chunkSize;
	long long _uploadGranularity;
	BOOL _isPaused;
	BOOL _isRestartedUpload;
	BOOL _shouldInitiateOffsetQuery;
	BOOL _useBackgroundSessionOnChunkFetchers;
	long long _currentOffset;
	NSDictionary* _responseHeaders;
	long long _statusCode;
	GTMSessionFetcher* _fetcherInFlight;
	BOOL _isSubdataGenerating;
	NSURL* _uploadFileURL;
	NSURLRequest* _lastChunkRequest;

}

@property (retain) NSURLRequest * lastChunkRequest;                                   //@synthesize lastChunkRequest=_lastChunkRequest - In the implementation block
@property (retain) NSURL * uploadLocationURL;                                         //@synthesize uploadLocationURL=_uploadLocationURL - In the implementation block
@property (retain) NSData * uploadData;                                               //@synthesize uploadData=_uploadData - In the implementation block
@property (retain) NSURL * uploadFileURL;                                             //@synthesize uploadFileURL=_uploadFileURL - In the implementation block
@property (retain) NSFileHandle * uploadFileHandle;                                   //@synthesize uploadFileHandle=_uploadFileHandle - In the implementation block
@property (copy,readonly) id uploadDataProvider; 
@property (copy) NSString * uploadMIMEType;                                           //@synthesize uploadMIMEType=_uploadMIMEType - In the implementation block
@property (assign) long long chunkSize;                                               //@synthesize chunkSize=_chunkSize - In the implementation block
@property (assign) long long currentOffset;                                           //@synthesize currentOffset=_currentOffset - In the implementation block
@property (retain) GTMSessionFetcher * chunkFetcher;                                  //@synthesize chunkFetcher=_chunkFetcher - In the implementation block
@property (readonly) GTMSessionFetcher * activeFetcher; 
@property (retain) NSDictionary * responseHeaders; 
@property (assign) long long statusCode; 
@property (readonly) NSObject*<OS_dispatch_queue> delegateCallbackQueue;              //@synthesize delegateCallbackQueue=_delegateCallbackQueue - In the implementation block
@property (readonly) id delegateCompletionHandler;                                    //@synthesize delegateCompletionHandler=_delegateCompletionHandler - In the implementation block
+(id)uploadFetchersForBackgroundSessions;
+(id)uploadFetcherWithRequest:(id)arg1 fetcherService:(id)arg2 ;
+(id)uploadFetcherWithLocation:(id)arg1 uploadMIMEType:(id)arg2 chunkSize:(long long)arg3 fetcherService:(id)arg4 ;
+(id)uploadFetcherPointerArrayForBackgroundSessions;
+(id)uploadFetcherForSessionIdentifierMetadata:(id)arg1 ;
+(unsigned long long)uploadStatusFromResponseHeaders:(id)arg1 ;
+(void)removePointer:(void*)arg1 fromPointerArray:(id)arg2 ;
+(id)uploadFetcherWithRequest:(id)arg1 uploadMIMEType:(id)arg2 chunkSize:(long long)arg3 fetcherService:(id)arg4 ;
+(id)uploadFetcherForSessionIdentifier:(id)arg1 ;
+(void)load;
-(void)stopFetching;
-(BOOL)waitForCompletionWithTimeout:(double)arg1 ;
-(void)beginFetchWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)stopFetchReleasingCallbacks:(BOOL)arg1 ;
-(BOOL)shouldReleaseCallbacksUponCompletion;
-(BOOL)useBackgroundSession;
-(void)setUseBackgroundSession:(BOOL)arg1 ;
-(void)setLocationURL:(id)arg1 uploadMIMEType:(id)arg2 chunkSize:(long long)arg3 ;
-(void)setUploadFileLength:(long long)arg1 ;
-(void)setUploadFileURL:(NSURL *)arg1 ;
-(GTMSessionFetcher *)chunkFetcher;
-(void)attachSendProgressBlockToChunkFetcher:(id)arg1 ;
-(void)chunkFetcher:(id)arg1 finishedWithData:(id)arg2 error:(id)arg3 ;
-(void)setupRequestHeaders;
-(long long)fullUploadLength;
-(void)setUploadMIMEType:(NSString *)arg1 ;
-(NSURL *)uploadFileURL;
-(id)uploadChunkUnavailableErrorWithDescription:(id)arg1 ;
-(void)generateChunkSubdataFromFileURL:(id)arg1 offset:(long long)arg2 length:(long long)arg3 response:(/*^block*/id)arg4 ;
-(void)generateChunkSubdataFromFileHandle:(id)arg1 offset:(long long)arg2 length:(long long)arg3 response:(/*^block*/id)arg4 ;
-(void)sendQueryForUploadOffsetWithFetcherProperties:(id)arg1 ;
-(void)beginChunkFetches;
-(void)invokeFinalCallbackWithData:(id)arg1 error:(id)arg2 shouldInvalidateLocation:(BOOL)arg3 ;
-(void)generateChunkSubdataWithOffset:(long long)arg1 length:(long long)arg2 response:(/*^block*/id)arg3 ;
-(void)retrieveUploadChunkGranularityFromResponseHeaders:(id)arg1 ;
-(id)prematureFailureErrorWithUserInfo:(id)arg1 ;
-(void)setUploadLocationURL:(NSURL *)arg1 ;
-(void)uploadNextChunkWithOffset:(long long)arg1 ;
-(void)invokeDelegateWithDidSendBytes:(long long)arg1 totalBytesSent:(long long)arg2 totalBytesExpectedToSend:(long long)arg3 ;
-(void)releaseUploadAndBaseCallbacks;
-(void)uploadNextChunkWithOffset:(long long)arg1 fetcherProperties:(id)arg2 ;
-(id)uploadFetcherWithProperties:(id)arg1 isQueryFetch:(BOOL)arg2 ;
-(void)queryFetcher:(id)arg1 finishedWithData:(id)arg2 error:(id)arg3 ;
-(void)beginChunkFetcher:(id)arg1 offset:(long long)arg2 ;
-(NSURL *)uploadLocationURL;
-(NSString *)uploadMIMEType;
-(id)uploadSessionIdentifierMetadata;
-(void)setLastChunkRequest:(NSURLRequest *)arg1 ;
-(void)destroyChunkFetcher;
-(void)sendCancelUploadWithFetcherProperties:(id)arg1 ;
-(void)setUploadData:(NSData *)arg1 ;
-(void)setUploadFileHandle:(NSFileHandle *)arg1 ;
-(NSFileHandle *)uploadFileHandle;
-(void)setUploadDataLength:(long long)arg1 provider:(/*^block*/id)arg2 ;
-(id)uploadDataProvider;
-(void)pauseFetching;
-(void)resumeFetching;
-(GTMSessionFetcher *)activeFetcher;
-(NSObject*<OS_dispatch_queue>)delegateCallbackQueue;
-(id)delegateCompletionHandler;
-(void)setChunkFetcher:(GTMSessionFetcher *)arg1 ;
-(NSURLRequest *)lastChunkRequest;
-(long long)currentOffset;
-(void)URLSession:(id)arg1 task:(id)arg2 didSendBodyData:(long long)arg3 totalBytesSent:(long long)arg4 totalBytesExpectedToSend:(long long)arg5 ;
-(BOOL)isPaused;
-(void)setCompletionHandler:(/*^block*/id)arg1 ;
-(long long)statusCode;
-(NSDictionary *)responseHeaders;
-(NSData *)uploadData;
-(void)setStatusCode:(long long)arg1 ;
-(long long)chunkSize;
-(void)setChunkSize:(long long)arg1 ;
-(void)setCurrentOffset:(long long)arg1 ;
@end

