/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <UIKit/UIWebViewDelegate.h>

@class NSURL, NSString;

@interface GTMSessionFetcherLoggingWebViewController : UIViewController <UIWebViewDelegate> {

	BOOL opensScrolledToEnd_;
	NSURL* htmlURL_;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithURL:(id)arg1 title:(id)arg2 opensScrolledToEnd:(BOOL)arg3 ;
-(void)didTapBackButton:(id)arg1 ;
-(void)loadView;
-(void)viewDidLoad;
-(id)webView;
-(void)webViewDidFinishLoad:(id)arg1 ;
@end

