/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSOperationQueue;


@protocol GTMSessionFetcherServiceProtocol <NSObject>
@property (retain) NSObject*<OS_dispatch_queue> callbackQueue; 
@property (assign) BOOL reuseSession; 
@property (readonly) NSOperationQueue * delegateQueue; 
@required
-(id)fetcherWithRequest:(id)arg1;
-(id)sessionForFetcherCreation;
-(void)fetcherDidCreateSession:(id)arg1;
-(BOOL)fetcherShouldBeginFetching:(id)arg1;
-(void)fetcherDidBeginFetching:(id)arg1;
-(void)fetcherDidStop:(id)arg1;
-(BOOL)isDelayingFetcher:(id)arg1;
-(BOOL)reuseSession;
-(void)setReuseSession:(BOOL)arg1;
-(NSOperationQueue *)delegateQueue;
-(id)session;
-(id)sessionDelegate;
-(void)setCallbackQueue:(id)arg1;
-(NSObject*<OS_dispatch_queue>)callbackQueue;

@end

