/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/GTMSessionFetcherServiceProtocol.h>

@protocol OS_dispatch_queue, GTMFetcherAuthorizationProtocol;
@class NSOperationQueue, NSMutableDictionary, GTMSessionFetcherSessionDelegateDispatcher, NSObject, NSHTTPCookieStorage, NSString, NSURLCredential, NSMutableArray, NSURLSessionConfiguration, NSArray, NSDictionary;

@interface GTMSessionFetcherService : NSObject <GTMSessionFetcherServiceProtocol> {

	NSMutableDictionary* _delayedFetchersByHost;
	NSMutableDictionary* _runningFetchersByHost;
	unsigned long long _maxRunningFetchersPerHost;
	GTMSessionFetcherSessionDelegateDispatcher* _delegateDispatcher;
	NSObject*<OS_dispatch_queue> _callbackQueue;
	NSHTTPCookieStorage* _cookieStorage;
	NSString* _userAgent;
	double _timeout;
	NSURLCredential* _credential;
	NSURLCredential* _proxyCredential;
	long long _cookieStorageMethod;
	id<GTMFetcherAuthorizationProtocol> _authorizer;
	NSMutableArray* _stoppedFetchersToWaitFor;
	BOOL _allowLocalhostRequest;
	BOOL _allowInvalidServerCertificates;
	BOOL _retryEnabled;
	NSURLSessionConfiguration* _configuration;
	/*^block*/id _configurationBlock;
	NSArray* _allowedInsecureSchemes;
	/*^block*/id _retryBlock;
	double _maxRetryInterval;
	double _minRetryInterval;
	NSDictionary* _properties;
	double _unusedSessionTimeout;
	/*^block*/id _testBlock;

}

@property (assign) long long cookieStorageMethod; 
@property (retain) NSDictionary * delayedFetchersByHost; 
@property (retain) NSDictionary * runningFetchersByHost; 
@property (assign) unsigned long long maxRunningFetchersPerHost;                //@synthesize maxRunningFetchersPerHost=_maxRunningFetchersPerHost - In the implementation block
@property (retain) NSURLSessionConfiguration * configuration;                   //@synthesize configuration=_configuration - In the implementation block
@property (copy) id configurationBlock;                                         //@synthesize configurationBlock=_configurationBlock - In the implementation block
@property (retain) NSHTTPCookieStorage * cookieStorage;                         //@synthesize cookieStorage=_cookieStorage - In the implementation block
@property (retain) NSObject*<OS_dispatch_queue> callbackQueue;                  //@synthesize callbackQueue=_callbackQueue - In the implementation block
@property (retain) NSURLCredential * credential;                                //@synthesize credential=_credential - In the implementation block
@property (retain) NSURLCredential * proxyCredential;                           //@synthesize proxyCredential=_proxyCredential - In the implementation block
@property (copy) NSArray * allowedInsecureSchemes;                              //@synthesize allowedInsecureSchemes=_allowedInsecureSchemes - In the implementation block
@property (assign) BOOL allowLocalhostRequest;                                  //@synthesize allowLocalhostRequest=_allowLocalhostRequest - In the implementation block
@property (assign) BOOL allowInvalidServerCertificates;                         //@synthesize allowInvalidServerCertificates=_allowInvalidServerCertificates - In the implementation block
@property (getter=isRetryEnabled) BOOL retryEnabled;                            //@synthesize retryEnabled=_retryEnabled - In the implementation block
@property (copy) id retryBlock;                                                 //@synthesize retryBlock=_retryBlock - In the implementation block
@property (assign) double maxRetryInterval;                                     //@synthesize maxRetryInterval=_maxRetryInterval - In the implementation block
@property (assign) double minRetryInterval;                                     //@synthesize minRetryInterval=_minRetryInterval - In the implementation block
@property (copy) NSDictionary * properties;                                     //@synthesize properties=_properties - In the implementation block
@property (copy) NSString * userAgent;                                          //@synthesize userAgent=_userAgent - In the implementation block
@property (retain) id<GTMFetcherAuthorizationProtocol> authorizer; 
@property (assign) BOOL reuseSession; 
@property (assign) double unusedSessionTimeout;                                 //@synthesize unusedSessionTimeout=_unusedSessionTimeout - In the implementation block
@property (copy) id testBlock;                                                  //@synthesize testBlock=_testBlock - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (readonly) NSOperationQueue * delegateQueue; 
+(id)mockFetcherServiceWithFakedData:(id)arg1 fakedError:(id)arg2 ;
+(unsigned long long)numberOfNonBackgroundSessionFetchers:(id)arg1 ;
-(void)setCookieStorageMethod:(long long)arg1 ;
-(long long)cookieStorageMethod;
-(BOOL)waitForCompletionOfAllFetchersWithTimeout:(double)arg1 ;
-(id)fetcherWithRequest:(id)arg1 ;
-(void)setAuthorizer:(id<GTMFetcherAuthorizationProtocol>)arg1 ;
-(void)setRetryEnabled:(BOOL)arg1 ;
-(void)setMaxRetryInterval:(double)arg1 ;
-(id)fetcherWithURL:(id)arg1 ;
-(id)sessionForFetcherCreation;
-(void)fetcherDidCreateSession:(id)arg1 ;
-(BOOL)fetcherShouldBeginFetching:(id)arg1 ;
-(void)fetcherDidBeginFetching:(id)arg1 ;
-(void)fetcherDidStop:(id)arg1 ;
-(id<GTMFetcherAuthorizationProtocol>)authorizer;
-(BOOL)isDelayingFetcher:(id)arg1 ;
-(void)setRetryBlock:(id)arg1 ;
-(void)setTestBlock:(id)arg1 ;
-(BOOL)isRetryEnabled;
-(double)maxRetryInterval;
-(void)setMinRetryInterval:(double)arg1 ;
-(id)fetcherWithURLString:(id)arg1 ;
-(double)minRetryInterval;
-(NSURLCredential *)proxyCredential;
-(void)setProxyCredential:(NSURLCredential *)arg1 ;
-(id)retryBlock;
-(NSArray *)allowedInsecureSchemes;
-(void)setAllowedInsecureSchemes:(NSArray *)arg1 ;
-(BOOL)allowLocalhostRequest;
-(void)setAllowLocalhostRequest:(BOOL)arg1 ;
-(BOOL)allowInvalidServerCertificates;
-(void)setAllowInvalidServerCertificates:(BOOL)arg1 ;
-(NSHTTPCookieStorage *)cookieStorage;
-(id)testBlock;
-(void)detachAuthorizer;
-(id)fetcherWithRequest:(id)arg1 fetcherClass:(Class)arg2 ;
-(void)addRunningFetcher:(id)arg1 forHost:(id)arg2 ;
-(void)addDelayedFetcher:(id)arg1 forHost:(id)arg2 ;
-(id)delegateDispatcherForFetcher:(id)arg1 ;
-(void)startFetcher:(id)arg1 ;
-(unsigned long long)numberOfRunningFetchers;
-(unsigned long long)numberOfDelayedFetchers;
-(id)issuedFetchers;
-(void)stopFetcher:(id)arg1 ;
-(void)abandonDispatcher;
-(BOOL)reuseSession;
-(void)setReuseSession:(BOOL)arg1 ;
-(unsigned long long)numberOfFetchers;
-(id)issuedFetchersWithRequestURL:(id)arg1 ;
-(void)stopAllFetchers;
-(void)resetSession;
-(double)unusedSessionTimeout;
-(void)setUnusedSessionTimeout:(double)arg1 ;
-(NSDictionary *)runningFetchersByHost;
-(void)setRunningFetchersByHost:(NSDictionary *)arg1 ;
-(NSDictionary *)delayedFetchersByHost;
-(void)setDelayedFetchersByHost:(NSDictionary *)arg1 ;
-(unsigned long long)maxRunningFetchersPerHost;
-(void)setMaxRunningFetchersPerHost:(unsigned long long)arg1 ;
-(NSOperationQueue *)delegateQueue;
-(void)setCredential:(NSURLCredential *)arg1 ;
-(id)session;
-(void)dealloc;
-(id)init;
-(void)setConfiguration:(NSURLSessionConfiguration *)arg1 ;
-(NSURLSessionConfiguration *)configuration;
-(id)configurationBlock;
-(void)setConfigurationBlock:(id)arg1 ;
-(NSDictionary *)properties;
-(void)setProperties:(NSDictionary *)arg1 ;
-(id)sessionDelegate;
-(void)setCookieStorage:(NSHTTPCookieStorage *)arg1 ;
-(void)setUserAgent:(NSString *)arg1 ;
-(NSString *)userAgent;
-(NSURLCredential *)credential;
-(void)setCallbackQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(NSObject*<OS_dispatch_queue>)callbackQueue;
@end

