/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/pokemongo-Structs.h>
#import <UIKit/UITextFieldDelegate.h>
#import <UIKit/UITextViewDelegate.h>

@class UITextView, UIToolbar, NSArray, UITextField, UIView, NSString;

@interface KeyboardDelegate : NSObject <UITextFieldDelegate, UITextViewDelegate> {

	UITextView* textView;
	UIToolbar* viewToolbar;
	NSArray* viewToolbarItems;
	UITextField* textField;
	UIToolbar* fieldToolbar;
	NSArray* fieldToolbarItems;
	UIView* inputView;
	UIView* editView;
	CGRect _area;
	NSString* initialText;
	long long keyboardType;
	BOOL _multiline;
	BOOL _inputHidden;
	BOOL _active;
	BOOL _done;
	BOOL _canceled;
	BOOL _rotating;
	NSString* text;
	CGRect area;

}

@property (getter=queryArea,nonatomic,readonly) CGRect area; 
@property (nonatomic,readonly) BOOL active;                                               //@synthesize active=_active - In the implementation block
@property (nonatomic,readonly) BOOL done;                                                 //@synthesize done=_done - In the implementation block
@property (nonatomic,readonly) BOOL canceled;                                             //@synthesize canceled=_canceled - In the implementation block
@property (setter=setText:,getter=getText,nonatomic,retain) NSString * text; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)Instance;
+(void)Initialize;
+(void)StartReorientation;
+(void)FinishReorientation;
-(void)positionInput:(CGRect)arg1 x:(float)arg2 y:(float)arg3 ;
-(void)systemHideKeyboard;
-(void)textInputDone:(id)arg1 ;
-(void)textInputCancel:(id)arg1 ;
-(CreateToolbarResult)createToolbarWithView:(id)arg1 ;
-(void)setTextInputTraits:(id)arg1 withParam:(SCD_Struct_Ke3)arg2 withCap:(long long)arg3 ;
-(void)shouldHideInput:(BOOL)arg1 ;
-(void)updateInputHidden;
-(void)setTextWorkaround:(id)arg1 text:(id)arg2 ;
-(void)setKeyboardParams:(SCD_Struct_Ke3)arg1 ;
-(CGRect)queryArea;
-(id)getText;
-(void)showUI;
-(void)hideUI;
-(void)hide;
-(void)show;
-(id)init;
-(void)setText:(NSString *)arg1 ;
-(BOOL)active;
-(BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(NSRange)arg2 replacementString:(id)arg3 ;
-(BOOL)textFieldShouldReturn:(id)arg1 ;
-(void)keyboardDidShow:(id)arg1 ;
-(BOOL)textViewShouldBeginEditing:(id)arg1 ;
-(BOOL)done;
-(void)keyboardDidChangeFrame:(id)arg1 ;
-(BOOL)canceled;
-(void)keyboardWillHide:(id)arg1 ;
@end

