/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <pokemongo/GKGameCenterControllerDelegate.h>

@class GKGameCenterViewController, NSString;

@interface LeaderboardWrapper : UIViewController <GKGameCenterControllerDelegate> {

	GKGameCenterViewController* m_LeaderboardController;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)showLeaderboardUI:(id)arg1 withTimeScope:(long long)arg2 ;
-(void)gameCenterViewControllerDidFinish:(id)arg1 ;
@end

