/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/UnityViewControllerListener.h>

@class MPMoviePlayerController, CancelOnTouchView, UIColor, NSString;

@interface MPVideoPlayback : NSObject <UnityViewControllerListener> {

	MPMoviePlayerController* moviePlayer;
	CancelOnTouchView* cancelOnTouchView;
	UIColor* bgColor;
	long long controlMode;
	long long scalingMode;
	BOOL cancelOnTouch;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)viewDidLayoutSubviews:(id)arg1 ;
-(void)actuallyStartTheMovie:(id)arg1 ;
-(void)moviePlayBackDidFinish:(id)arg1 ;
-(void)moviePlayBackSourceTypeAvailable:(id)arg1 ;
-(void)moviePlayBackMediaTypesAvailable:(id)arg1 ;
-(void)moviePlayBackNaturalSizeAvailable:(id)arg1 ;
-(void)audioRouteChanged:(id)arg1 ;
-(id)initAndPlay:(id)arg1 bgColor:(id)arg2 controls:(long long)arg3 scaling:(long long)arg4 cancelOnTouch:(BOOL)arg5 ;
-(void)dealloc;
-(void)finish;
@end

