/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <pokemongo/pokemongo-Structs.h>
@class CMMotionManager, NSOperationQueue;

@interface NIAIosSensorManager : NSObject {

	SensorUpdate* _sensorProto;
	CMMotionManager* _motionManager;
	NSOperationQueue* _sensorQueue;
	IosSensorProvider* _sensorProvider;

}

@property (assign,nonatomic) IosSensorProvider* sensorProvider;              //@synthesize sensorProvider=_sensorProvider - In the implementation block
-(void)setSensorProvider:(IosSensorProvider*)arg1 ;
-(void)processDeviceMotion:(id)arg1 error:(id)arg2 ;
-(IosSensorProvider*)sensorProvider;
-(void)dealloc;
-(id)init;
-(void)stop;
-(void)start;
@end

