/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <pokemongo/pokemongo-Structs.h>
@class CMMotionActivityManager, NSOperationQueue;

@interface NIAIosActivityManager : NSObject {

	Activity* _userActivity;
	CMMotionActivityManager* _activityManager;
	NSOperationQueue* _activityQueue;
	IosActivityProvider* _activityProvider;

}

@property (assign,nonatomic) IosActivityProvider* activityProvider;              //@synthesize activityProvider=_activityProvider - In the implementation block
-(int)mapConfidenceToInt:(long long)arg1 ;
-(IosActivityProvider*)activityProvider;
-(void)handleActivityUpdate:(id)arg1 ;
-(void)checkAuthorization:(/*^block*/id)arg1 ;
-(void)setActivityProvider:(IosActivityProvider*)arg1 ;
-(void)setLocationProvider:(IosActivityProvider*)arg1 ;
-(void)dealloc;
-(id)init;
-(void)stop;
-(void)start;
@end

