/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface PlayerWrapper : NSObject
+(void)loadUserPhotoAsyncAndTriggerCallbackWhenNeeded:(id)arg1 withCondition:(BOOL)arg2 index:(int)arg3 totalSize:(int)arg4 ;
+(void)processUsers:(id)arg1 withCondition:(BOOL)arg2 friendCallback:(/*^block*/id)arg3 ;
+(void)loadUserIds:(id)arg1 withCondition:(BOOL)arg2 ;
+(void)processNonFriendUsersUsingNewAPI:(id)arg1 withFriends:(id)arg2 ;
+(void)loadFriends;
@end

