/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface PLCrashReportApplicationInfo : NSObject {

	NSString* _applicationIdentifier;
	NSString* _applicationVersion;
	NSString* _applicationMarketingVersion;

}

@property (nonatomic,readonly) NSString * applicationIdentifier;                    //@synthesize applicationIdentifier=_applicationIdentifier - In the implementation block
@property (nonatomic,readonly) NSString * applicationVersion;                       //@synthesize applicationVersion=_applicationVersion - In the implementation block
@property (nonatomic,readonly) NSString * applicationMarketingVersion;              //@synthesize applicationMarketingVersion=_applicationMarketingVersion - In the implementation block
-(id)initWithApplicationIdentifier:(id)arg1 applicationVersion:(id)arg2 applicationMarketingVersion:(id)arg3 ;
-(NSString *)applicationMarketingVersion;
-(void)dealloc;
-(NSString *)applicationIdentifier;
-(NSString *)applicationVersion;
@end

