/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSDate, PLCrashReportProcessorInfo;

@interface PLCrashReportSystemInfo : NSObject {

	int _operatingSystem;
	NSString* _osVersion;
	NSString* _osBuild;
	int _architecture;
	NSDate* _timestamp;
	PLCrashReportProcessorInfo* _processorInfo;
	unsigned long long _memoryUsage;
	unsigned long long _freeDiskSpace;

}

@property (nonatomic,readonly) int operatingSystem;                                     //@synthesize operatingSystem=_operatingSystem - In the implementation block
@property (nonatomic,readonly) NSString * operatingSystemVersion;                       //@synthesize osVersion=_osVersion - In the implementation block
@property (nonatomic,readonly) NSString * operatingSystemBuild;                         //@synthesize osBuild=_osBuild - In the implementation block
@property (nonatomic,readonly) int architecture;                                        //@synthesize architecture=_architecture - In the implementation block
@property (nonatomic,readonly) NSDate * timestamp;                                      //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) PLCrashReportProcessorInfo * processorInfo;              //@synthesize processorInfo=_processorInfo - In the implementation block
@property (nonatomic,readonly) unsigned long long memoryUsage;                          //@synthesize memoryUsage=_memoryUsage - In the implementation block
@property (nonatomic,readonly) unsigned long long freeDiskSpace;                        //@synthesize freeDiskSpace=_freeDiskSpace - In the implementation block
-(NSString *)operatingSystemBuild;
-(PLCrashReportProcessorInfo *)processorInfo;
-(unsigned long long)freeDiskSpace;
-(id)initWithOperatingSystem:(int)arg1 operatingSystemVersion:(id)arg2 operatingSystemBuild:(id)arg3 architecture:(int)arg4 processorInfo:(id)arg5 timestamp:(id)arg6 memoryUsage:(unsigned long long)arg7 freeDiskSpace:(unsigned long long)arg8 ;
-(id)initWithOperatingSystem:(int)arg1 operatingSystemVersion:(id)arg2 architecture:(int)arg3 timestamp:(id)arg4 memoryUsage:(unsigned long long)arg5 freeDiskSpace:(unsigned long long)arg6 ;
-(id)initWithOperatingSystem:(int)arg1 operatingSystemVersion:(id)arg2 operatingSystemBuild:(id)arg3 architecture:(int)arg4 timestamp:(id)arg5 memoryUsage:(unsigned long long)arg6 freeDiskSpace:(unsigned long long)arg7 ;
-(int)operatingSystem;
-(NSString *)operatingSystemVersion;
-(void)dealloc;
-(NSDate *)timestamp;
-(int)architecture;
-(unsigned long long)memoryUsage;
@end

