/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <pokemongo/pokemongo-Structs.h>
@class PLCrashReportSystemInfo, PLCrashReportMachineInfo, PLCrashReportApplicationInfo, PLCrashReportProcessInfo, PLCrashReportSignalInfo, PLCrashReportMachExceptionInfo, NSArray, PLCrashReportExceptionInfo;

@interface PLCrashReport : NSObject {

	PLCrashReportDecoder* _decoder;
	PLCrashReportSystemInfo* _systemInfo;
	PLCrashReportMachineInfo* _machineInfo;
	PLCrashReportApplicationInfo* _applicationInfo;
	PLCrashReportProcessInfo* _processInfo;
	PLCrashReportSignalInfo* _signalInfo;
	PLCrashReportMachExceptionInfo* _machExceptionInfo;
	NSArray* _threads;
	NSArray* _images;
	PLCrashReportExceptionInfo* _exceptionInfo;
	CFUUIDRef _uuid;

}

@property (nonatomic,readonly) PLCrashReportSystemInfo * systemInfo;                            //@synthesize systemInfo=_systemInfo - In the implementation block
@property (nonatomic,readonly) BOOL hasMachineInfo; 
@property (nonatomic,readonly) PLCrashReportMachineInfo * machineInfo;                          //@synthesize machineInfo=_machineInfo - In the implementation block
@property (nonatomic,readonly) PLCrashReportApplicationInfo * applicationInfo;                  //@synthesize applicationInfo=_applicationInfo - In the implementation block
@property (nonatomic,readonly) BOOL hasProcessInfo; 
@property (nonatomic,readonly) PLCrashReportProcessInfo * processInfo;                          //@synthesize processInfo=_processInfo - In the implementation block
@property (nonatomic,readonly) PLCrashReportSignalInfo * signalInfo;                            //@synthesize signalInfo=_signalInfo - In the implementation block
@property (nonatomic,readonly) PLCrashReportMachExceptionInfo * machExceptionInfo;              //@synthesize machExceptionInfo=_machExceptionInfo - In the implementation block
@property (nonatomic,readonly) NSArray * threads;                                               //@synthesize threads=_threads - In the implementation block
@property (nonatomic,readonly) NSArray * images;                                                //@synthesize images=_images - In the implementation block
@property (nonatomic,readonly) BOOL hasExceptionInfo; 
@property (nonatomic,readonly) PLCrashReportExceptionInfo * exceptionInfo;                      //@synthesize exceptionInfo=_exceptionInfo - In the implementation block
@property (nonatomic,readonly) CFUUIDRef uuidRef;                                               //@synthesize uuid=_uuid - In the implementation block
-(Plcrash__CrashReport*)decodeCrashData:(id)arg1 error:(id*)arg2 ;
-(id)extractMachineInfo:(Plcrash__CrashReport__MachineInfo*)arg1 error:(id*)arg2 ;
-(id)extractApplicationInfo:(Plcrash__CrashReport__ApplicationInfo*)arg1 error:(id*)arg2 ;
-(id)extractProcessInfo:(Plcrash__CrashReport__ProcessInfo*)arg1 error:(id*)arg2 ;
-(id)extractSignalInfo:(Plcrash__CrashReport__Signal*)arg1 error:(id*)arg2 ;
-(id)extractMachExceptionInfo:(Plcrash__CrashReport__Signal__MachException*)arg1 error:(id*)arg2 ;
-(id)extractThreadInfo:(Plcrash__CrashReport*)arg1 error:(id*)arg2 ;
-(id)extractImageInfo:(Plcrash__CrashReport*)arg1 error:(id*)arg2 ;
-(id)extractExceptionInfo:(Plcrash__CrashReport__Exception*)arg1 error:(id*)arg2 ;
-(id)extractProcessorInfo:(Plcrash__CrashReport__Processor*)arg1 error:(id*)arg2 ;
-(id)extractSymbolInfo:(Plcrash__CrashReport__Symbol*)arg1 error:(id*)arg2 ;
-(id)extractStackFrameInfo:(Plcrash__CrashReport__Thread__StackFrame*)arg1 error:(id*)arg2 ;
-(id)extractSystemInfo:(Plcrash__CrashReport__SystemInfo*)arg1 processorInfo:(id)arg2 error:(id*)arg3 ;
-(id)synthesizeProcessorInfoFromArchitecture:(int)arg1 error:(id*)arg2 ;
-(id)imageForAddress:(unsigned long long)arg1 ;
-(BOOL)hasMachineInfo;
-(BOOL)hasProcessInfo;
-(BOOL)hasExceptionInfo;
-(PLCrashReportMachineInfo *)machineInfo;
-(PLCrashReportSignalInfo *)signalInfo;
-(PLCrashReportMachExceptionInfo *)machExceptionInfo;
-(PLCrashReportExceptionInfo *)exceptionInfo;
-(CFUUIDRef)uuidRef;
-(void)dealloc;
-(PLCrashReportProcessInfo *)processInfo;
-(NSArray *)images;
-(NSArray *)threads;
-(PLCrashReportApplicationInfo *)applicationInfo;
-(id)initWithData:(id)arg1 error:(id*)arg2 ;
-(PLCrashReportSystemInfo *)systemInfo;
@end

