/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <pokemongo/pokemongo-Structs.h>
@interface PLCrashMachExceptionServer : NSObject {

	plcrash_exception_server_context* _serverContext;

}

@property (nonatomic,readonly) unsigned serverThread; 
-(id)initWithCallBack:(/*function pointer*/void*)arg1 context:(void*)arg2 error:(id*)arg3 ;
-(id)exceptionPortWithMask:(unsigned)arg1 error:(id*)arg2 ;
-(unsigned)copySendRightForServerAndReturningError:(id*)arg1 ;
-(unsigned)serverThread;
-(void)dealloc;
@end

