/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSArray;

@interface PLCrashReportExceptionInfo : NSObject {

	NSString* _name;
	NSString* _reason;
	NSArray* _stackFrames;

}

@property (nonatomic,readonly) NSString * exceptionName;                //@synthesize name=_name - In the implementation block
@property (nonatomic,readonly) NSString * exceptionReason;              //@synthesize reason=_reason - In the implementation block
@property (nonatomic,readonly) NSArray * stackFrames;                   //@synthesize stackFrames=_stackFrames - In the implementation block
-(id)initWithExceptionName:(id)arg1 reason:(id)arg2 ;
-(id)initWithExceptionName:(id)arg1 reason:(id)arg2 stackFrames:(id)arg3 ;
-(NSArray *)stackFrames;
-(NSString *)exceptionName;
-(NSString *)exceptionReason;
-(void)dealloc;
@end

