/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class PLCrashReportSymbolInfo;

@interface PLCrashReportStackFrameInfo : NSObject {

	unsigned long long _instructionPointer;
	PLCrashReportSymbolInfo* _symbolInfo;

}

@property (nonatomic,readonly) unsigned long long instructionPointer;              //@synthesize instructionPointer=_instructionPointer - In the implementation block
@property (nonatomic,readonly) PLCrashReportSymbolInfo * symbolInfo;               //@synthesize symbolInfo=_symbolInfo - In the implementation block
-(id)initWithInstructionPointer:(unsigned long long)arg1 symbolInfo:(id)arg2 ;
-(unsigned long long)instructionPointer;
-(PLCrashReportSymbolInfo *)symbolInfo;
-(void)dealloc;
@end

