/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface PurchasableItemDetails : NSObject {

	NSString* _itemId;
	NSString* _title;
	NSString* _itemDescription;
	NSString* _price;

}

@property (readonly) NSString * itemId;                       //@synthesize itemId=_itemId - In the implementation block
@property (readonly) NSString * title;                        //@synthesize title=_title - In the implementation block
@property (readonly) NSString * itemDescription;              //@synthesize itemDescription=_itemDescription - In the implementation block
@property (readonly) NSString * price;                        //@synthesize price=_price - In the implementation block
-(id)init:(id)arg1 title:(id)arg2 description:(id)arg3 price:(id)arg4 ;
-(NSString *)itemId;
-(NSString *)title;
-(NSString *)price;
-(NSString *)itemDescription;
@end

