/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/pokemongo-Structs.h>
#import <pokemongo/RenderPluginDelegate.h>

@class NSArray;

@interface RenderPluginArrayDelegate : RenderPluginDelegate {

	NSArray* delegateArray;

}

@property (nonatomic,retain) NSArray * delegateArray; 
-(void)mainDisplayInited:(UnityDisplaySurfaceBase*)arg1 ;
-(void)onFrameResolved;
-(void)onBeforeMainDisplaySurfaceRecreate:(RenderingSurfaceParamsRef)arg1 ;
-(void)onAfterMainDisplaySurfaceRecreate;
-(void)willTerminate:(id)arg1 ;
-(NSArray *)delegateArray;
-(void)setDelegateArray:(NSArray *)arg1 ;
-(void)willResignActive:(id)arg1 ;
-(void)didBecomeActive:(id)arg1 ;
-(void)didEnterBackground:(id)arg1 ;
-(void)willEnterForeground:(id)arg1 ;
@end

