/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface UnityPLCrashReportProcessorInfo : NSObject {

	int _typeEncoding;
	unsigned long long _type;
	unsigned long long _subtype;

}

@property (nonatomic,readonly) int typeEncoding;                        //@synthesize typeEncoding=_typeEncoding - In the implementation block
@property (nonatomic,readonly) unsigned long long type;                 //@synthesize type=_type - In the implementation block
@property (nonatomic,readonly) unsigned long long subtype;              //@synthesize subtype=_subtype - In the implementation block
-(id)initWithTypeEncoding:(int)arg1 type:(unsigned long long)arg2 subtype:(unsigned long long)arg3 ;
-(unsigned long long)type;
-(unsigned long long)subtype;
-(int)typeEncoding;
@end

