/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/pokemongo-Structs.h>
#import <pokemongo/UnityRenderingView.h>

@interface UnityView : UnityRenderingView {

	CGSize _surfaceSize;
	int _curOrientation;
	BOOL _recreateView;

}

@property (nonatomic,readonly) int contentOrientation;              //@synthesize curOrientation=_curOrientation - In the implementation block
-(BOOL)processTouches:(id)arg1 ;
-(void)togglePatrolPause;
-(void)togglePatrol;
-(void)toggleWalk;
-(void)incrementSpeed;
-(void)recreateGLESSurfaceIfNeeded;
-(void)recreateGLESSurface;
-(int)contentOrientation;
-(void)onUpdateSurfaceSize:(CGSize)arg1 ;
-(void)initImpl:(CGRect)arg1 scaleFactor:(double)arg2 ;
-(id)initWithFrame:(CGRect)arg1 scaleFactor:(double)arg2 ;
-(id)initFromMainScreen;
-(void)willRotateToOrientation:(long long)arg1 fromOrientation:(long long)arg2 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
-(void)didRotate;
@end

