/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, UnityPLCrashReportProcessorInfo;

@interface UnityPLCrashReportMachineInfo : NSObject {

	NSString* _modelName;
	UnityPLCrashReportProcessorInfo* _processorInfo;
	unsigned long long _processorCount;
	unsigned long long _logicalProcessorCount;

}

@property (nonatomic,readonly) NSString * modelName;                                         //@synthesize modelName=_modelName - In the implementation block
@property (nonatomic,readonly) UnityPLCrashReportProcessorInfo * processorInfo;              //@synthesize processorInfo=_processorInfo - In the implementation block
@property (nonatomic,readonly) unsigned long long processorCount;                            //@synthesize processorCount=_processorCount - In the implementation block
@property (nonatomic,readonly) unsigned long long logicalProcessorCount;                     //@synthesize logicalProcessorCount=_logicalProcessorCount - In the implementation block
-(id)initWithModelName:(id)arg1 processorInfo:(id)arg2 processorCount:(unsigned long long)arg3 logicalProcessorCount:(unsigned long long)arg4 ;
-(UnityPLCrashReportProcessorInfo *)processorInfo;
-(unsigned long long)logicalProcessorCount;
-(NSString *)modelName;
-(void)dealloc;
-(unsigned long long)processorCount;
@end

