/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class UnityPLCrashReportProcessorInfo, NSString;

@interface UnityPLCrashReportBinaryImageInfo : NSObject {

	UnityPLCrashReportProcessorInfo* _processorInfo;
	unsigned long long _baseAddress;
	unsigned long long _imageSize;
	NSString* _imageName;
	BOOL _hasImageUUID;
	NSString* _imageUUID;

}

@property (nonatomic,readonly) UnityPLCrashReportProcessorInfo * codeType;              //@synthesize processorInfo=_processorInfo - In the implementation block
@property (nonatomic,readonly) unsigned long long imageBaseAddress;                     //@synthesize baseAddress=_baseAddress - In the implementation block
@property (nonatomic,readonly) unsigned long long imageSize;                            //@synthesize imageSize=_imageSize - In the implementation block
@property (nonatomic,readonly) NSString * imageName;                                    //@synthesize imageName=_imageName - In the implementation block
@property (nonatomic,readonly) BOOL hasImageUUID;                                       //@synthesize hasImageUUID=_hasImageUUID - In the implementation block
@property (nonatomic,readonly) NSString * imageUUID;                                    //@synthesize imageUUID=_imageUUID - In the implementation block
-(unsigned long long)imageBaseAddress;
-(id)initWithCodeType:(id)arg1 baseAddress:(unsigned long long)arg2 size:(unsigned long long)arg3 name:(id)arg4 uuid:(id)arg5 ;
-(BOOL)hasImageUUID;
-(void)dealloc;
-(unsigned long long)imageSize;
-(NSString *)imageName;
-(NSString *)imageUUID;
-(UnityPLCrashReportProcessorInfo *)codeType;
@end

