/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSURLConnectionDataDelegate.h>

@class NSMutableURLRequest, NSURLConnection, NSURL, NSString, NSData, NSCondition;

@interface UnityWWWConnectionDelegate : NSObject <NSURLConnectionDataDelegate> {

	void* _udata;
	NSMutableURLRequest* _request;
	NSURLConnection* _connection;
	NSURL* _url;
	NSString* _user;
	NSString* _password;
	NSString* _responseHeader;
	long long _status;
	unsigned long long _estimatedLength;
	unsigned long long _dataRecievd;
	int _retryCount;
	BOOL shouldAbort;
	BOOL _manuallyHandleRedirect;
	NSData* _data;
	NSCondition* _condition;

}

@property (assign,nonatomic) void* udata;                                //@synthesize udata=_udata - In the implementation block
@property (nonatomic,retain) NSURL * url;                                //@synthesize url=_url - In the implementation block
@property (nonatomic,retain) NSString * user;                            //@synthesize user=_user - In the implementation block
@property (nonatomic,retain) NSString * password;                        //@synthesize password=_password - In the implementation block
@property (nonatomic,retain) NSMutableURLRequest * request;              //@synthesize request=_request - In the implementation block
@property (nonatomic,retain) NSURLConnection * connection;               //@synthesize connection=_connection - In the implementation block
@property (nonatomic,retain) NSCondition * condition;                    //@synthesize condition=_condition - In the implementation block
@property (assign,nonatomic) BOOL manuallyHandleRedirect;                //@synthesize manuallyHandleRedirect=_manuallyHandleRedirect - In the implementation block
@property (nonatomic,retain,readonly) NSData * data;                     //@synthesize data=_data - In the implementation block
@property (assign,nonatomic) BOOL shouldAbort; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)newDelegateWithURL:(id)arg1 udata:(void*)arg2 ;
+(id)newDelegateWithCStringURL:(const char*)arg1 udata:(void*)arg2 ;
+(id)newRequestForHTTPMethod:(id)arg1 url:(id)arg2 headers:(id)arg3 ;
-(id)extractUserPassFromUrl:(id)arg1 ;
-(void)setUdata:(void*)arg1 ;
-(id)initWithURL:(id)arg1 udata:(void*)arg2 ;
-(BOOL)manuallyHandleRedirect;
-(BOOL)shouldAbort;
-(void*)udata;
-(BOOL)connection:(id)arg1 handleAuthenticationChallenge:(id)arg2 ;
-(void)setShouldAbort:(BOOL)arg1 ;
-(void)setManuallyHandleRedirect:(BOOL)arg1 ;
-(NSString *)user;
-(NSString *)password;
-(void)setUser:(NSString *)arg1 ;
-(void)setPassword:(NSString *)arg1 ;
-(NSURL *)url;
-(NSMutableURLRequest *)request;
-(NSData *)data;
-(void)setUrl:(NSURL *)arg1 ;
-(void)connection:(id)arg1 didFailWithError:(id)arg2 ;
-(void)connection:(id)arg1 didReceiveData:(id)arg2 ;
-(void)connectionDidFinishLoading:(id)arg1 ;
-(void)connection:(id)arg1 didReceiveResponse:(id)arg2 ;
-(NSCondition *)condition;
-(void)setCondition:(NSCondition *)arg1 ;
-(NSURLConnection *)connection;
-(void)setConnection:(NSURLConnection *)arg1 ;
-(void)cleanup;
-(void)handleResponse:(id)arg1 ;
-(void)connection:(id)arg1 willSendRequestForAuthenticationChallenge:(id)arg2 ;
-(void)connection:(id)arg1 didSendBodyData:(long long)arg2 totalBytesWritten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4 ;
-(id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3 ;
-(void)setRequest:(NSMutableURLRequest *)arg1 ;
@end

