/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface UnityPLCrashReportSignalInfo : NSObject {

	NSString* _name;
	NSString* _code;
	unsigned long long _address;

}

@property (nonatomic,readonly) NSString * name;                         //@synthesize name=_name - In the implementation block
@property (nonatomic,readonly) NSString * code;                         //@synthesize code=_code - In the implementation block
@property (nonatomic,readonly) unsigned long long address;              //@synthesize address=_address - In the implementation block
-(id)initWithSignalName:(id)arg1 code:(id)arg2 address:(unsigned long long)arg3 ;
-(unsigned long long)address;
-(void)dealloc;
-(NSString *)name;
-(NSString *)code;
@end

