/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/pokemongo-Structs.h>
#import <UIKit/UIApplicationDelegate.h>

@protocol RenderPluginDelegate;
@class UIWindow, UnityView, CADisplayLink, UIView, UIViewController, DisplayConnection, UnityViewControllerBase, NSString;

@interface UnityAppController : NSObject <UIApplicationDelegate> {

	UnityView* _unityView;
	CADisplayLink* _displayLink;
	UIWindow* _window;
	UIView* _rootView;
	UIViewController* _rootController;
	UIView* _snapshotView;
	DisplayConnection* _mainDisplay;
	UnityViewControllerBase* _viewControllerForOrientation[5];
	long long _curOrientation;
	id<RenderPluginDelegate> _renderDelegate;
	CADisplayLink* _unityDisplayLink;
	/*^block*/id _quitHandler;

}

@property (nonatomic,readonly) int renderingAPI; 
@property (assign,nonatomic) BOOL paused; 
@property (nonatomic,retain) UIWindow * window; 
@property (nonatomic,copy,readonly) UnityView * unityView;                              //@synthesize unityView=_unityView - In the implementation block
@property (nonatomic,copy,readonly) CADisplayLink * unityDisplayLink;                   //@synthesize unityDisplayLink=_unityDisplayLink - In the implementation block
@property (nonatomic,copy,readonly) UIView * rootView;                                  //@synthesize rootView=_rootView - In the implementation block
@property (nonatomic,copy,readonly) UIViewController * rootViewController;              //@synthesize rootController=_rootController - In the implementation block
@property (nonatomic,copy,readonly) DisplayConnection * mainDisplay;                    //@synthesize mainDisplay=_mainDisplay - In the implementation block
@property (nonatomic,readonly) long long interfaceOrientation;                          //@synthesize curOrientation=_curOrientation - In the implementation block
@property (nonatomic,retain) id renderDelegate;                                         //@synthesize renderDelegate=_renderDelegate - In the implementation block
@property (nonatomic,copy) id quitHandler;                                              //@synthesize quitHandler=_quitHandler - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)application:(id)arg1 didRegisterUserNotificationSettings:(id)arg2 ;
-(void)checkOrientationRequest;
-(id)topMostController;
-(void)showGameUI;
-(id)createUnityView;
-(void)createUI;
-(id)createSnapshotView;
-(id)createUnityViewControllerForOrientation:(long long)arg1 ;
-(id)createAutorotatingUnityViewController;
-(id)createRootViewControllerForOrientation:(long long)arg1 ;
-(void)updateAppOrientation:(long long)arg1 ;
-(id)createRootViewController;
-(void)willStartWithViewController:(id)arg1 ;
-(void)willTransitionToViewController:(id)arg1 fromViewController:(id)arg2 ;
-(void)interfaceWillChangeOrientationTo:(long long)arg1 ;
-(void)transitionToViewController:(id)arg1 ;
-(void)interfaceDidChangeOrientationFrom:(long long)arg1 ;
-(void)orientInterface:(long long)arg1 ;
-(void)orientUnity:(long long)arg1 ;
-(void)repaintDisplayLink;
-(void)repaint;
-(void)createDisplayLink;
-(void)callbackGfxInited;
-(void)callbackPresent:(const UnityFrameStats*)arg1 ;
-(void)callbackFramerateChange:(int)arg1 ;
-(void)selectRenderingAPI;
-(int)renderingAPI;
-(void)setPaused:(BOOL)arg1 ;
-(BOOL)paused;
-(void)shouldAttachRenderDelegate;
-(id)quitHandler;
-(void)preStartUnity;
-(UnityView *)unityView;
-(void)startUnity:(id)arg1 ;
-(CADisplayLink *)unityDisplayLink;
-(void)setQuitHandler:(id)arg1 ;
-(UIWindow *)window;
-(id)init;
-(long long)interfaceOrientation;
-(BOOL)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4 ;
-(void)applicationDidReceiveMemoryWarning:(id)arg1 ;
-(void)applicationWillTerminate:(id)arg1 ;
-(void)applicationDidBecomeActive:(id)arg1 ;
-(void)applicationWillResignActive:(id)arg1 ;
-(void)applicationDidEnterBackground:(id)arg1 ;
-(void)applicationWillEnterForeground:(id)arg1 ;
-(unsigned long long)application:(id)arg1 supportedInterfaceOrientationsForWindow:(id)arg2 ;
-(BOOL)application:(id)arg1 willFinishLaunchingWithOptions:(id)arg2 ;
-(BOOL)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2 ;
-(void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2 fetchCompletionHandler:(/*^block*/id)arg3 ;
-(DisplayConnection *)mainDisplay;
-(void)setWindow:(UIWindow *)arg1 ;
-(UIViewController *)rootViewController;
-(void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2 ;
-(void)application:(id)arg1 didReceiveLocalNotification:(id)arg2 ;
-(void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2 ;
-(void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2 ;
-(UIView *)rootView;
-(id)renderDelegate;
-(void)setRenderDelegate:(id)arg1 ;
@end

