/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/UpsightDataStoreInterface.h>

@class NSURL, NSString, NSEntityDescription, NSManagedObjectModel, NSPersistentStoreCoordinator, NSManagedObjectContext, NSOperationQueue, NSMutableDictionary, NSMutableArray;

@interface UpsightDataStore : NSObject <UpsightDataStoreInterface> {

	NSURL* _dataStoreURL;
	NSString* _dataStoreType;
	NSEntityDescription* _entityDescription;
	NSManagedObjectModel* _objectModel;
	NSPersistentStoreCoordinator* _storeCoordinator;
	NSManagedObjectContext* _objectContext;
	NSOperationQueue* _callbackQueue;
	id _contextChangeObserver;
	NSMutableDictionary* _observers;
	NSMutableArray* _defaultObservers;

}

@property (nonatomic,retain) NSURL * dataStoreURL;                                         //@synthesize dataStoreURL=_dataStoreURL - In the implementation block
@property (nonatomic,retain) NSString * dataStoreType;                                     //@synthesize dataStoreType=_dataStoreType - In the implementation block
@property (nonatomic,retain) NSEntityDescription * entityDescription;                      //@synthesize entityDescription=_entityDescription - In the implementation block
@property (nonatomic,retain) NSManagedObjectModel * objectModel;                           //@synthesize objectModel=_objectModel - In the implementation block
@property (nonatomic,retain) NSPersistentStoreCoordinator * storeCoordinator;              //@synthesize storeCoordinator=_storeCoordinator - In the implementation block
@property (nonatomic,retain) NSManagedObjectContext * objectContext;                       //@synthesize objectContext=_objectContext - In the implementation block
@property (nonatomic,retain) NSOperationQueue * callbackQueue;                             //@synthesize callbackQueue=_callbackQueue - In the implementation block
@property (nonatomic,retain) id contextChangeObserver;                                     //@synthesize contextChangeObserver=_contextChangeObserver - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * observers;                              //@synthesize observers=_observers - In the implementation block
@property (nonatomic,retain) NSMutableArray * defaultObservers;                            //@synthesize defaultObservers=_defaultObservers - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)dataStoreURLWithDirectory:(id)arg1 fileNamePrefix:(id)arg2 ;
+(void)removeFileAtURL:(id)arg1 ;
+(BOOL)createDirectoryWithURL:(id)arg1 ;
+(id)preReleaseDefaultStore;
+(void)removePreReleaseDataStore;
+(id)defaultStore;
-(void)addObserver:(id)arg1 selector:(SEL)arg2 type:(id)arg3 queue:(id)arg4 predicate:(id)arg5 ;
-(void)removeObserver:(id)arg1 type:(id)arg2 ;
-(void)remove:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)queryObjects:(id)arg1 predicate:(id)arg2 ;
-(void)store:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)initWithDatabaseDirectoryURL:(id)arg1 fileNamePrefix:(id)arg2 ;
-(NSURL *)dataStoreURL;
-(id)initWithDataStoreURL:(id)arg1 ;
-(void)buildCoreDataStack;
-(id)contextChangeObserver;
-(void)setContextChangeObserver:(id)arg1 ;
-(NSPersistentStoreCoordinator *)storeCoordinator;
-(NSManagedObjectContext *)objectContext;
-(void)handleContextChangeNotification:(id)arg1 ;
-(id)generateObjects:(id)arg1 ;
-(void)notifyObservers:(id)arg1 action:(unsigned long long)arg2 ;
-(NSMutableArray *)defaultObservers;
-(void)addDefaultObserver:(id)arg1 selector:(SEL)arg2 queue:(id)arg3 ;
-(void)addObserver:(id)arg1 selector:(SEL)arg2 type:(id)arg3 queue:(id)arg4 ;
-(void)removeObserver:(id)arg1 type:(id)arg2 predicate:(id)arg3 ;
-(void)addObserver:(id)arg1 selector:(SEL)arg2 type:(id)arg3 ;
-(void)addDefaultObserver:(id)arg1 selector:(SEL)arg2 ;
-(void)removeDefaultObserver:(id)arg1 ;
-(void)removeObjects:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)initWithStorageType:(id)arg1 ;
-(void)setDataStoreURL:(NSURL *)arg1 ;
-(void)setEntityDescription:(NSEntityDescription *)arg1 ;
-(void)setStoreCoordinator:(NSPersistentStoreCoordinator *)arg1 ;
-(void)setObjectContext:(NSManagedObjectContext *)arg1 ;
-(void)setDefaultObservers:(NSMutableArray *)arg1 ;
-(NSEntityDescription *)entityDescription;
-(void)dealloc;
-(id)init;
-(void)setObservers:(NSMutableDictionary *)arg1 ;
-(NSMutableDictionary *)observers;
-(NSString *)dataStoreType;
-(void)setDataStoreType:(NSString *)arg1 ;
-(void)setCallbackQueue:(NSOperationQueue *)arg1 ;
-(NSOperationQueue *)callbackQueue;
-(NSManagedObjectModel *)objectModel;
-(void)setObjectModel:(NSManagedObjectModel *)arg1 ;
@end

