/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol USAnalyticsInterface, USBillboardManager, UpsightDataStoreInterface;
@class NSString;

@interface Upsight : NSObject {

	id<USAnalyticsInterface> _analytics;
	id<USBillboardManager> _billboardManager;
	id<UpsightDataStoreInterface> _dataStore;
	NSString* _token;

}

@property (nonatomic,retain) id<USAnalyticsInterface> analytics;                   //@synthesize analytics=_analytics - In the implementation block
@property (nonatomic,retain) id<USBillboardManager> billboardManager;              //@synthesize billboardManager=_billboardManager - In the implementation block
@property (nonatomic,retain) id<UpsightDataStoreInterface> dataStore;              //@synthesize dataStore=_dataStore - In the implementation block
@property (nonatomic,retain) NSString * token;                                     //@synthesize token=_token - In the implementation block
+(id)senderID;
+(void)setPluginVersion:(id)arg1 ;
+(BOOL)optOutStatus;
+(void)setOptOutStatus:(BOOL)arg1 ;
+(void)recordAnalyticsEventWithName:(id)arg1 properties:(id)arg2 ;
+(void)recordMilestoneEventForScope:(id)arg1 properties:(id)arg2 ;
+(void)recordMonetizationEventWithResolution:(unsigned long long)arg1 totalPrice:(float)arg2 currency:(id)arg3 product:(id)arg4 properties:(id)arg5 ;
+(void)recordInAppPurchaseEventWithResolution:(unsigned long long)arg1 product:(id)arg2 quantity:(unsigned long long)arg3 price:(float)arg4 currency:(id)arg5 transactionIdentifier:(id)arg6 properties:(id)arg7 ;
+(id)variableObserver;
+(id)billboardForScope:(id)arg1 ;
+(id)sharedUpsight;
+(void)recordMonetizationEventWithResolution:(unsigned long long)arg1 currency:(id)arg2 quantity:(unsigned long long)arg3 product:(id)arg4 price:(float)arg5 properties:(id)arg6 ;
+(void)recordMilestoneEventForScope:(id)arg1 ;
+(void)setLocation:(id)arg1 ;
+(id)token;
+(long long)defaultLogLevel;
+(id)publicKey;
+(void)setDefaultLogLevel:(long long)arg1 ;
-(void)setAnalytics:(id<USAnalyticsInterface>)arg1 ;
-(void)setBillboardManager:(id<USBillboardManager>)arg1 ;
-(id<USAnalyticsInterface>)analytics;
-(id<USBillboardManager>)billboardManager;
-(id)init;
-(NSString *)token;
-(void)setToken:(NSString *)arg1 ;
-(id)initWithDataStore:(id)arg1 ;
-(void)setDataStore:(id<UpsightDataStoreInterface>)arg1 ;
-(id<UpsightDataStoreInterface>)dataStore;
@end

