/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UpsightDynamicConfigurationDelegate;
@class NSDictionary;

@interface UpsightDynamicConfiguration : NSObject {

	id<UpsightDynamicConfigurationDelegate> _delegate;
	NSDictionary* _configuration;

}

@property (assign,nonatomic,__weak) id<UpsightDynamicConfigurationDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) NSDictionary * configuration;                                         //@synthesize configuration=_configuration - In the implementation block
+(id)defaultConfiguration;
-(void)willUnload;
-(void)updateConfiguration:(id)arg1 ;
-(void)setDelegate:(id<UpsightDynamicConfigurationDelegate>)arg1 ;
-(id<UpsightDynamicConfigurationDelegate>)delegate;
-(void)setConfiguration:(NSDictionary *)arg1 ;
-(NSDictionary *)configuration;
-(id)initWithConfiguration:(id)arg1 ;
@end

