/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UpsightDataStoreInterface <NSObject>
@required
-(void)addObserver:(id)arg1 selector:(SEL)arg2 type:(id)arg3 queue:(id)arg4 predicate:(id)arg5;
-(void)removeObserver:(id)arg1 type:(id)arg2;
-(void)remove:(id)arg1 completion:(/*^block*/id)arg2;
-(id)queryObjects:(id)arg1 predicate:(id)arg2;
-(void)store:(id)arg1 completion:(/*^block*/id)arg2;
-(void)addObserver:(id)arg1 selector:(SEL)arg2 type:(id)arg3 queue:(id)arg4;
-(void)removeObserver:(id)arg1 type:(id)arg2 predicate:(id)arg3;
-(void)addObserver:(id)arg1 selector:(SEL)arg2 type:(id)arg3;
-(void)addDefaultObserver:(id)arg1 selector:(SEL)arg2;
-(void)removeDefaultObserver:(id)arg1;
-(void)removeObjects:(id)arg1 completion:(/*^block*/id)arg2;

@end

