/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol USActionMapDelegate;
@class NSMutableSet, NSString, NSDictionary, NSSet;

@interface USActionMap : NSObject {

	BOOL _actionMapDisposed;
	NSMutableSet* _executingActions;
	NSString* _actionFactoryType;
	NSString* _ID;
	id<USActionMapDelegate> _delegate;
	NSDictionary* _triggerToActionsMap;
	NSSet* _actionTypesIndex;

}

@property (nonatomic,readonly) NSString * actionFactoryType;                                 //@synthesize actionFactoryType=_actionFactoryType - In the implementation block
@property (nonatomic,readonly) NSString * ID;                                                //@synthesize ID=_ID - In the implementation block
@property (assign,nonatomic,__weak) id<USActionMapDelegate> delegate;                        //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) NSDictionary * triggerToActionsMap;                           //@synthesize triggerToActionsMap=_triggerToActionsMap - In the implementation block
@property (nonatomic,readonly) NSMutableSet * executingActions;                              //@synthesize executingActions=_executingActions - In the implementation block
@property (nonatomic,readonly) NSSet * actionTypesIndex;                                     //@synthesize actionTypesIndex=_actionTypesIndex - In the implementation block
@property (assign,getter=isActionMapDisposed,nonatomic) BOOL actionMapDisposed;              //@synthesize actionMapDisposed=_actionMapDisposed - In the implementation block
+(void)registerActionHandlersWithRegistry:(id)arg1 ;
-(id)initWithActionMapDictionary:(id)arg1 factory:(id)arg2 ;
-(void)executeActionsForTrigger:(id)arg1 ;
-(void)onDisposeActionCalled;
-(NSDictionary *)triggerToActionsMap;
-(NSMutableSet *)executingActions;
-(BOOL)isActionMapDisposed;
-(void)onActionMapDidFinishExecution;
-(NSSet *)actionTypesIndex;
-(void)setActionMapDisposed:(BOOL)arg1 ;
-(BOOL)containsActionsWithType:(id)arg1 ;
-(NSString *)actionFactoryType;
-(void)setDelegate:(id<USActionMapDelegate>)arg1 ;
-(id)init;
-(id<USActionMapDelegate>)delegate;
-(NSString *)ID;
@end

