/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/USActionMapDelegate.h>
#import <pokemongo/USActionMapManagerInterface.h>

@protocol UpsightDataStoreInterface;
@class USActionFactory, NSMutableSet, NSString;

@interface USActionMapManager : NSObject <USActionMapDelegate, USActionMapManagerInterface> {

	USActionFactory* _actionsFactory;
	NSMutableSet* _actionMaps;
	NSMutableSet* _observers;
	id<UpsightDataStoreInterface> _dataStore;

}

@property (nonatomic,readonly) id<UpsightDataStoreInterface> dataStore;              //@synthesize dataStore=_dataStore - In the implementation block
@property (readonly) USActionFactory * actionsFactory;                               //@synthesize actionsFactory=_actionsFactory - In the implementation block
@property (nonatomic,readonly) NSMutableSet * actionMaps;                            //@synthesize actionMaps=_actionMaps - In the implementation block
@property (nonatomic,readonly) NSMutableSet * observers;                             //@synthesize observers=_observers - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (readonly) id<USActionHandlerRegistry> handlerRegistry; 
-(void)onDidStoreActionMap:(id)arg1 action:(unsigned long long)arg2 ;
-(USActionFactory *)actionsFactory;
-(void)onDidCreateActionMap:(id)arg1 ;
-(NSMutableSet *)actionMaps;
-(void)actionMapDidFinishExecution:(id)arg1 ;
-(id<USActionHandlerRegistry>)handlerRegistry;
-(void)dealloc;
-(id)init;
-(void)addObserver:(id)arg1 ;
-(void)removeObserver:(id)arg1 ;
-(NSMutableSet *)observers;
-(id)initWithDataStore:(id)arg1 ;
-(id<UpsightDataStoreInterface>)dataStore;
@end

