/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/USActionFactoryInterface.h>
#import <pokemongo/USActionHandlerRegistry.h>

@class NSMutableDictionary, NSDictionary, NSString;

@interface USActionFactory : NSObject <USActionFactoryInterface, USActionHandlerRegistry> {

	NSMutableDictionary* _actionToHandlerMap;
	NSDictionary* _actionToBuilderMap;

}

@property (readonly) NSMutableDictionary * actionToHandlerMap;              //@synthesize actionToHandlerMap=_actionToHandlerMap - In the implementation block
@property (readonly) NSDictionary * actionToBuilderMap;                     //@synthesize actionToBuilderMap=_actionToBuilderMap - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)registerHandler:(/*^block*/id)arg1 forActionType:(id)arg2 ;
-(/*^block*/id)buildContentBuilder;
-(/*^block*/id)presentScopedContentBuilder;
-(/*^block*/id)presentScopelessContentBuilder;
-(/*^block*/id)sendEventBuilder;
-(/*^block*/id)disposeActionMapBuilder;
-(/*^block*/id)triggerIfContentAvailableBuilder;
-(/*^block*/id)notifyRewardsBuilder;
-(/*^block*/id)notifyPurchasesBuilder;
-(/*^block*/id)triggerActionBuilder;
-(/*^block*/id)openURLBuilder;
-(/*^block*/id)sendFormDataBuilder;
-(/*^block*/id)presentCloseButtonBuilder;
-(/*^block*/id)associateOnceBuilder;
-(/*^block*/id)modifyValueBuilder;
-(/*^block*/id)UXMEnumerateBuilder;
-(/*^block*/id)setBundleIDBuilder;
-(/*^block*/id)openInAppStoreBuilder;
-(/*^block*/id)notifyUXMValuesSynchronized;
-(NSDictionary *)actionToBuilderMap;
-(NSMutableDictionary *)actionToHandlerMap;
-(id)actionWithDictionary:(id)arg1 map:(id)arg2 ;
@end

