/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <pokemongo/pokemongo-Structs.h>
@class USEventDataAssociationMap;

@interface USAssociationDataProvider : NSObject {

	USEventDataAssociationMap* _oneTimeAssociationMap;

}

@property (nonatomic,retain) USEventDataAssociationMap * oneTimeAssociationMap;              //@synthesize oneTimeAssociationMap=_oneTimeAssociationMap - In the implementation block
+(id)sharedProvider;
-(void)addOneTimeAssociation:(id)arg1 ;
-(id)obtainAndRemoveAssociatedUpsightDataForEventType:(id)arg1 upsightData:(id)arg2 ;
-(id)initWithAssociationMap:(id)arg1 ;
-(USEventDataAssociationMap *)oneTimeAssociationMap;
-(void)setOneTimeAssociationMap:(USEventDataAssociationMap *)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

