/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/USConfigurationBase.h>

@class NSArray, NSString;

@interface USAttributeSet : USConfigurationBase {

	NSArray* _excludes;
	NSArray* _includes;
	NSString* _name;

}

@property (nonatomic,retain) NSArray * excludes;              //@synthesize excludes=_excludes - In the implementation block
@property (nonatomic,retain) NSArray * includes;              //@synthesize includes=_includes - In the implementation block
@property (nonatomic,retain) NSString * name;                 //@synthesize name=_name - In the implementation block
+(BOOL)isValidConfigurationDictionary:(id)arg1 ;
+(id)requiredKeys;
-(void)setName:(NSString *)arg1 ;
-(NSString *)name;
-(NSArray *)includes;
-(NSArray *)excludes;
-(void)setIncludes:(NSArray *)arg1 ;
-(void)setExcludes:(NSArray *)arg1 ;
-(id)initWithConfigurationDictionary:(id)arg1 ;
@end

