/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol USBatcherDelegate, USDataSenderInterface;
@class NSOperationQueue, USEventBatch, NSMutableSet, NSTimer, NSMutableDictionary, USRequestAttributeSetBuilder, NSString, USQueueConfiguration;

@interface USBatcher : NSObject {

	id<USBatcherDelegate> _delegate;
	NSOperationQueue* _operationQueue;
	USEventBatch* _activeBatch;
	NSMutableSet* _pendingBatches;
	id<USDataSenderInterface> _dataSender;
	NSTimer* _sendTimer;
	NSTimer* _retryTimer;
	NSMutableDictionary* _retryInfos;
	USRequestAttributeSetBuilder* _attributeBuilder;
	NSString* _attributeSetName;
	USQueueConfiguration* _queueConfiguration;

}

@property (assign,nonatomic,__weak) id<USBatcherDelegate> delegate;                        //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) NSOperationQueue * operationQueue;                            //@synthesize operationQueue=_operationQueue - In the implementation block
@property (nonatomic,retain) USEventBatch * activeBatch;                                   //@synthesize activeBatch=_activeBatch - In the implementation block
@property (nonatomic,retain) NSMutableSet * pendingBatches;                                //@synthesize pendingBatches=_pendingBatches - In the implementation block
@property (nonatomic,retain) id<USDataSenderInterface> dataSender;                         //@synthesize dataSender=_dataSender - In the implementation block
@property (nonatomic,retain) NSTimer * sendTimer;                                          //@synthesize sendTimer=_sendTimer - In the implementation block
@property (nonatomic,retain) NSTimer * retryTimer;                                         //@synthesize retryTimer=_retryTimer - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * retryInfos;                             //@synthesize retryInfos=_retryInfos - In the implementation block
@property (nonatomic,retain) USRequestAttributeSetBuilder * attributeBuilder;              //@synthesize attributeBuilder=_attributeBuilder - In the implementation block
@property (nonatomic,retain) NSString * attributeSetName;                                  //@synthesize attributeSetName=_attributeSetName - In the implementation block
@property (retain) USQueueConfiguration * queueConfiguration;                              //@synthesize queueConfiguration=_queueConfiguration - In the implementation block
-(NSTimer *)sendTimer;
-(void)setSendTimer:(NSTimer *)arg1 ;
-(void)invalidateSendTimer;
-(void)setAttributeSetName:(NSString *)arg1 ;
-(USQueueConfiguration *)queueConfiguration;
-(void)setQueueConfiguration:(USQueueConfiguration *)arg1 ;
-(NSString *)attributeSetName;
-(USRequestAttributeSetBuilder *)attributeBuilder;
-(id<USDataSenderInterface>)dataSender;
-(id)initWithQueueConfiguration:(id)arg1 attributeSetName:(id)arg2 attributeBuilder:(id)arg3 dataSender:(id)arg4 operationQueue:(id)arg5 ;
-(void)setAttributeBuilder:(USRequestAttributeSetBuilder *)arg1 ;
-(void)setDataSender:(id<USDataSenderInterface>)arg1 ;
-(USEventBatch *)activeBatch;
-(void)dispatchBatch:(id)arg1 ;
-(void)setActiveBatch:(USEventBatch *)arg1 ;
-(void)installSendTimer;
-(NSMutableDictionary *)retryInfos;
-(id)retryInfoForBatch:(id)arg1 ;
-(id)endpointURLForQueueConfiguration:(id)arg1 ;
-(BOOL)shouldRetryBatch:(id)arg1 afterError:(id)arg2 ;
-(NSMutableSet *)pendingBatches;
-(void)installRetryTimer;
-(void)removeRetryInfoForBatch:(id)arg1 ;
-(void)onSendTimerDidFire:(id)arg1 ;
-(void)onRetryTimerDidFire:(id)arg1 ;
-(void)setPendingBatches:(NSMutableSet *)arg1 ;
-(void)setRetryInfos:(NSMutableDictionary *)arg1 ;
-(void)setDelegate:(id<USBatcherDelegate>)arg1 ;
-(id)init;
-(id<USBatcherDelegate>)delegate;
-(void)setOperationQueue:(NSOperationQueue *)arg1 ;
-(void)drain;
-(NSOperationQueue *)operationQueue;
-(NSTimer *)retryTimer;
-(void)setRetryTimer:(NSTimer *)arg1 ;
-(void)enqueueEvent:(id)arg1 ;
@end

