/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol USBillboardDelegate <NSObject>
@optional
-(void)billboardWillAppear:(id)arg1;
-(void)billboardDidAppear:(id)arg1;
-(void)billboardWillDismiss:(id)arg1;
-(void)billboardDidDismiss:(id)arg1;
-(void)billboard:(id)arg1 didReceiveReward:(id)arg2;
-(void)billboard:(id)arg1 didReceivePurchase:(id)arg2;

@required
-(id)presentingViewControllerForBillboard:(id)arg1;

@end

