/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/USBaseAction.h>

@class NSDictionary, NSString;

@interface USConditionalAction : USBaseAction {

	NSDictionary* _conditionParameters;
	NSString* _thenTrigger;
	NSString* _elseTrigger;

}

@property (nonatomic,readonly) NSDictionary * conditionParameters;              //@synthesize conditionParameters=_conditionParameters - In the implementation block
@property (nonatomic,readonly) NSString * thenTrigger;                          //@synthesize thenTrigger=_thenTrigger - In the implementation block
@property (nonatomic,readonly) NSString * elseTrigger;                          //@synthesize elseTrigger=_elseTrigger - In the implementation block
-(id)initWithParameters:(id)arg1 map:(id)arg2 handler:(/*^block*/id)arg3 ;
-(NSString *)thenTrigger;
-(NSString *)elseTrigger;
-(NSDictionary *)conditionParameters;
@end

