/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/UpsightStorableObject.h>

@class NSString, NSDictionary, NSNumber;

@interface USConfiguration : UpsightStorableObject {

	NSString* _configurationType;
	NSDictionary* _configurationDictionary;
	NSNumber* _sessionNumber;

}

@property (nonatomic,readonly) NSString * configurationType;                        //@synthesize configurationType=_configurationType - In the implementation block
@property (nonatomic,readonly) NSDictionary * configurationDictionary;              //@synthesize configurationDictionary=_configurationDictionary - In the implementation block
@property (nonatomic,readonly) NSNumber * sessionNumber;                            //@synthesize sessionNumber=_sessionNumber - In the implementation block
-(id)initWithType:(id)arg1 version:(id)arg2 ID:(id)arg3 ;
-(id)initWithConfigurationType:(id)arg1 configurationDictionary:(id)arg2 sessionNumber:(id)arg3 ;
-(NSString *)configurationType;
-(id)init;
-(NSNumber *)sessionNumber;
-(NSDictionary *)configurationDictionary;
@end

