/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/USContentUnitViewControllerDelegate.h>
#import <UIKit/UIViewControllerTransitioningDelegate.h>
#import <libobjc.A.dylib/SKStoreProductViewControllerDelegate.h>
#import <pokemongo/USBillboard.h>

@protocol USBillboardDelegate, USContentUnitBillboardDataSource;
@class NSString, USContentUnitViewController, SKStoreProductViewController;

@interface USContentUnitBillboard : NSObject <USContentUnitViewControllerDelegate, UIViewControllerTransitioningDelegate, SKStoreProductViewControllerDelegate, USBillboard> {

	BOOL _presenting;
	NSString* _scope;
	id<USBillboardDelegate> _delegate;
	USContentUnitViewController* _viewController;
	id<USContentUnitBillboardDataSource> _dataSource;
	SKStoreProductViewController* _inAppStoreController;

}

@property (retain) USContentUnitViewController * viewController;                     //@synthesize viewController=_viewController - In the implementation block
@property (__weak) id<USContentUnitBillboardDataSource> dataSource;                  //@synthesize dataSource=_dataSource - In the implementation block
@property (retain) SKStoreProductViewController * inAppStoreController;              //@synthesize inAppStoreController=_inAppStoreController - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (copy,readonly) NSString * scope;                                          //@synthesize scope=_scope - In the implementation block
@property (getter=isPresenting,readonly) BOOL presenting;                            //@synthesize presenting=_presenting - In the implementation block
@property (__weak) id<USBillboardDelegate> delegate;                                 //@synthesize delegate=_delegate - In the implementation block
@property (getter=isContentReady,readonly) BOOL contentReady; 
+(id)presentingControllerToScopeMap;
-(BOOL)isContentReady;
-(void)dismissViewControllerAnimated:(BOOL)arg1 ;
-(void)replacePresentedControllerWithViewController:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)onDidReceiveRewards:(id)arg1 ;
-(void)onDidReceivePurchases:(id)arg1 ;
-(void)replacePresentedControllerWithStoreUsingITunesIdentifier:(id)arg1 completion:(/*^block*/id)arg2 ;
-(SKStoreProductViewController *)inAppStoreController;
-(void)executeBlockOnMainQueue:(/*^block*/id)arg1 waitUntilFinished:(BOOL)arg2 ;
-(void)presentViewController:(id)arg1 presentingViewController:(id)arg2 animated:(BOOL)arg3 completion:(/*^block*/id)arg4 ;
-(void)setInAppStoreController:(SKStoreProductViewController *)arg1 ;
-(void)onDidEnterBackground:(id)arg1 ;
-(void)cleanupPresentingControllerToScopeMap;
-(void)contentUnitViewControllerWillDismiss:(id)arg1 ;
-(void)contentUnitViewControllerDidDismiss:(id)arg1 ;
-(id)initWithScope:(id)arg1 ;
-(BOOL)presentViewController:(id)arg1 animated:(BOOL)arg2 ;
-(void)setDataSource:(id<USContentUnitBillboardDataSource>)arg1 ;
-(void)setDelegate:(id<USBillboardDelegate>)arg1 ;
-(void)dealloc;
-(id<USContentUnitBillboardDataSource>)dataSource;
-(id<USBillboardDelegate>)delegate;
-(void)setViewController:(USContentUnitViewController *)arg1 ;
-(USContentUnitViewController *)viewController;
-(id)animationControllerForPresentedController:(id)arg1 presentingController:(id)arg2 sourceController:(id)arg3 ;
-(id)animationControllerForDismissedController:(id)arg1 ;
-(NSString *)scope;
-(BOOL)isPresenting;
-(void)productViewControllerDidFinish:(id)arg1 ;
@end

