/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UpsightDataStoreInterface, USAnalyticsInterface;
@class NSTimer, NSOperationQueue;

@interface USConfigurationManager : NSObject {

	id<UpsightDataStoreInterface> _dataStore;
	id<USAnalyticsInterface> _analytics;
	NSTimer* _sendTimer;
	NSOperationQueue* _queue;

}

@property (nonatomic,retain) id<UpsightDataStoreInterface> dataStore;                //@synthesize dataStore=_dataStore - In the implementation block
@property (assign,nonatomic,__weak) id<USAnalyticsInterface> analytics;              //@synthesize analytics=_analytics - In the implementation block
@property (nonatomic,retain) NSTimer * sendTimer;                                    //@synthesize sendTimer=_sendTimer - In the implementation block
@property (nonatomic,retain) NSOperationQueue * queue;                               //@synthesize queue=_queue - In the implementation block
+(id)defaultConfiguration;
-(void)setAnalytics:(id<USAnalyticsInterface>)arg1 ;
-(id<USAnalyticsInterface>)analytics;
-(void)configurationResponseDidUpdate:(id)arg1 action:(unsigned long long)arg2 ;
-(void)ownConfigurationDidUpdate:(id)arg1 action:(unsigned long long)arg2 ;
-(void)loadOwnConfiguration;
-(void)processStoredConfigurationResponses;
-(void)sendConfigurationRequest;
-(NSTimer *)sendTimer;
-(void)setSendTimer:(NSTimer *)arg1 ;
-(void)updateConfigurationsWithResponseObject:(id)arg1 ;
-(void)removeAllObjectsInDataStore:(id)arg1 withType:(id)arg2 predicate:(id)arg3 ;
-(void)applyConfiguration:(id)arg1 ;
-(void)invalidateSendTimer;
-(id)initWithDataStore:(id)arg1 analytics:(id)arg2 ;
-(NSOperationQueue *)queue;
-(void)setQueue:(NSOperationQueue *)arg1 ;
-(void)dealloc;
-(id)init;
-(id)initWithDataStore:(id)arg1 ;
-(void)setDataStore:(id<UpsightDataStoreInterface>)arg1 ;
-(id<UpsightDataStoreInterface>)dataStore;
-(void)setup;
@end

