/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol USContentUnitViewControllerCacheDelegate;
@class NSMutableDictionary;

@interface USContentUnitViewControllerCache : NSObject {

	NSMutableDictionary* _actionMapIDToControllerMap;
	id<USContentUnitViewControllerCacheDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<USContentUnitViewControllerCacheDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,readonly) NSMutableDictionary * actionMapIDToControllerMap;                        //@synthesize actionMapIDToControllerMap=_actionMapIDToControllerMap - In the implementation block
-(id)anyControllerForScope:(id)arg1 ;
-(id)controllerForActionMapID:(id)arg1 ;
-(NSMutableDictionary *)actionMapIDToControllerMap;
-(void)addController:(id)arg1 ;
-(void)removeController:(id)arg1 ;
-(void)setDelegate:(id<USContentUnitViewControllerCacheDelegate>)arg1 ;
-(id<USContentUnitViewControllerCacheDelegate>)delegate;
@end

