/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSURLConnectionDataDelegate.h>
#import <pokemongo/USDataSenderInterface.h>

@class NSOperationQueue, NSMutableDictionary, NSString;

@interface USDataSender : NSObject <NSURLConnectionDataDelegate, USDataSenderInterface> {

	NSOperationQueue* _sendQueue;
	NSMutableDictionary* _connections;
	unsigned long long _taskIdentifier;

}

@property (nonatomic,retain) NSMutableDictionary * connections;              //@synthesize connections=_connections - In the implementation block
@property (nonatomic,readonly) NSOperationQueue * sendQueue;                 //@synthesize sendQueue=_sendQueue - In the implementation block
@property (assign) unsigned long long taskIdentifier;                        //@synthesize taskIdentifier=_taskIdentifier - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)installObservers;
-(void)sendData:(id)arg1 toURL:(id)arg2 completionHandler:(/*^block*/id)arg3 queue:(id)arg4 ;
-(id)initWithSendQueue:(id)arg1 ;
-(void)endBackgroundTaskIfIdle;
-(BOOL)verifySignatureWithInfo:(id)arg1 ;
-(void)onApplicationDidEnterBackground:(id)arg1 ;
-(void)onApplicationWillEnterForeground:(id)arg1 ;
-(BOOL)hasIncompleteConnections;
-(void)setTaskIdentifier:(unsigned long long)arg1 ;
-(NSOperationQueue *)sendQueue;
-(void)dealloc;
-(id)init;
-(void)connection:(id)arg1 didFailWithError:(id)arg2 ;
-(void)connection:(id)arg1 didReceiveData:(id)arg2 ;
-(void)connectionDidFinishLoading:(id)arg1 ;
-(void)connection:(id)arg1 didReceiveResponse:(id)arg2 ;
-(NSMutableDictionary *)connections;
-(id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3 ;
-(void)setConnections:(NSMutableDictionary *)arg1 ;
-(unsigned long long)taskIdentifier;
-(void)startBackgroundTask;
-(void)endBackgroundTask;
@end

