/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/USBatcherDelegate.h>
#import <pokemongo/USDeliveryQueueInterface.h>

@protocol USDeliveryQueueDelegate, USDataSenderInterface;
@class USQueueConfiguration, USRequestAttributeSetBuilder, NSMutableDictionary, NSOperationQueue, NSString;

@interface USDeliveryQueue : NSObject <USBatcherDelegate, USDeliveryQueueInterface> {

	id<USDeliveryQueueDelegate> _delegate;
	USQueueConfiguration* _queueConfiguration;
	USRequestAttributeSetBuilder* _attributeBuilder;
	id<USDataSenderInterface> _dataSender;
	NSMutableDictionary* _attributeSetNameToBatcher;
	NSMutableDictionary* _eventIdToPacket;
	NSOperationQueue* _operationQueue;

}

@property (nonatomic,retain) USQueueConfiguration * queueConfiguration;                    //@synthesize queueConfiguration=_queueConfiguration - In the implementation block
@property (nonatomic,retain) USRequestAttributeSetBuilder * attributeBuilder;              //@synthesize attributeBuilder=_attributeBuilder - In the implementation block
@property (nonatomic,retain) id<USDataSenderInterface> dataSender;                         //@synthesize dataSender=_dataSender - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * attributeSetNameToBatcher;              //@synthesize attributeSetNameToBatcher=_attributeSetNameToBatcher - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * eventIdToPacket;                        //@synthesize eventIdToPacket=_eventIdToPacket - In the implementation block
@property (nonatomic,retain) NSOperationQueue * operationQueue;                            //@synthesize operationQueue=_operationQueue - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) NSString * name; 
@property (assign,nonatomic,__weak) id<USDeliveryQueueDelegate> delegate;                  //@synthesize delegate=_delegate - In the implementation block
-(USQueueConfiguration *)queueConfiguration;
-(void)enqueuePacket:(id)arg1 ;
-(void)setQueueConfiguration:(USQueueConfiguration *)arg1 ;
-(id)initWithQueueConfiguration:(id)arg1 attributeBuilder:(id)arg2 operationQueue:(id)arg3 dataSender:(id)arg4 ;
-(USRequestAttributeSetBuilder *)attributeBuilder;
-(NSMutableDictionary *)attributeSetNameToBatcher;
-(id<USDataSenderInterface>)dataSender;
-(NSMutableDictionary *)eventIdToPacket;
-(id)eventIDsFromEvents:(id)arg1 ;
-(id)packetsForEventIDs:(id)arg1 ;
-(void)batcher:(id)arg1 didDeliverEvents:(id)arg2 response:(id)arg3 ;
-(void)batcher:(id)arg1 didFailEventsDelivery:(id)arg2 error:(id)arg3 ;
-(void)setAttributeBuilder:(USRequestAttributeSetBuilder *)arg1 ;
-(void)setDataSender:(id<USDataSenderInterface>)arg1 ;
-(void)setAttributeSetNameToBatcher:(NSMutableDictionary *)arg1 ;
-(void)setEventIdToPacket:(NSMutableDictionary *)arg1 ;
-(void)setDelegate:(id<USDeliveryQueueDelegate>)arg1 ;
-(id)init;
-(id<USDeliveryQueueDelegate>)delegate;
-(NSString *)name;
-(void)setOperationQueue:(NSOperationQueue *)arg1 ;
-(void)drain;
-(NSOperationQueue *)operationQueue;
@end

