/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/UpsightStorableObject.h>

@protocol NSCoding;
@class NSString;

@interface USDefaultsStorable : UpsightStorableObject {

	NSString* _defaultName;
	id<NSCoding> _value;

}

@property (nonatomic,readonly) NSString * defaultName;              //@synthesize defaultName=_defaultName - In the implementation block
@property (nonatomic,retain) id<NSCoding> value;                    //@synthesize value=_value - In the implementation block
-(NSString *)defaultName;
-(id)initWithDefaultName:(id)arg1 ;
-(id)initWithType:(id)arg1 version:(id)arg2 ID:(id)arg3 ;
-(id<NSCoding>)value;
-(void)setValue:(id<NSCoding>)arg1 ;
@end

