/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/USConfigurationBase.h>

@class NSArray;

@interface USDispatcherConfiguration : USConfigurationBase {

	NSArray* _queues;
	NSArray* _routeFilters;
	NSArray* _attributeSets;
	NSArray* _attributeFilters;

}

@property (nonatomic,retain) NSArray * queues;                        //@synthesize queues=_queues - In the implementation block
@property (nonatomic,retain) NSArray * routeFilters;                  //@synthesize routeFilters=_routeFilters - In the implementation block
@property (nonatomic,retain) NSArray * attributeSets;                 //@synthesize attributeSets=_attributeSets - In the implementation block
@property (nonatomic,retain) NSArray * attributeFilters;              //@synthesize attributeFilters=_attributeFilters - In the implementation block
+(BOOL)isValidConfigurationDictionary:(id)arg1 ;
+(BOOL)isValidArrayOfConfigurationDictionaries:(id)arg1 forClass:(Class)arg2 ;
+(id)loadConfigurationDictionaryFromPlist;
+(id)defaultConfigurationDictionary;
+(id)defaultConfiguration;
-(NSArray *)routeFilters;
-(NSArray *)queues;
-(void)setAttributeSets:(NSArray *)arg1 ;
-(void)setQueues:(NSArray *)arg1 ;
-(NSArray *)attributeFilters;
-(void)setRouteFilters:(NSArray *)arg1 ;
-(void)setAttributeFilters:(NSArray *)arg1 ;
-(id)initWithConfigurationDictionary:(id)arg1 ;
-(NSArray *)attributeSets;
@end

