/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/USEvent.h>

@class NSString, NSDictionary;

@interface USDynamicEvent : USEvent

@property (nonatomic,readonly) NSString * dynamicType; 
@property (nonatomic,readonly) NSDictionary * upsightData; 
@property (nonatomic,readonly) NSDictionary * pubData; 
-(id)initWithType:(id)arg1 parameters:(id)arg2 ;
-(NSDictionary *)upsightData;
-(id)initWithWithParameters:(id)arg1 eventDictionary:(id)arg2 ;
-(NSDictionary *)pubData;
-(NSString *)dynamicType;
-(id)init;
@end

