/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSCoding.h>

@class USSession, NSString, NSDictionary;

@interface USEventParameters : NSObject <NSCoding> {

	double _timestamp;
	unsigned long long _eventNumber;
	USSession* _session;
	NSString* _eventType;
	NSString* _attributeSetName;
	NSDictionary* _userAttributes;
	NSDictionary* _pubData;
	NSDictionary* _upsightData;

}

@property (nonatomic,readonly) double timestamp;                                //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) unsigned long long eventNumber;                  //@synthesize eventNumber=_eventNumber - In the implementation block
@property (nonatomic,readonly) USSession * session;                             //@synthesize session=_session - In the implementation block
@property (nonatomic,copy) NSString * eventType;                                //@synthesize eventType=_eventType - In the implementation block
@property (nonatomic,copy) NSString * attributeSetName;                         //@synthesize attributeSetName=_attributeSetName - In the implementation block
@property (nonatomic,copy,readonly) NSDictionary * userAttributes;              //@synthesize userAttributes=_userAttributes - In the implementation block
@property (nonatomic,copy) NSDictionary * pubData;                              //@synthesize pubData=_pubData - In the implementation block
@property (nonatomic,copy) NSDictionary * upsightData;                          //@synthesize upsightData=_upsightData - In the implementation block
-(void)setUpsightData:(NSDictionary *)arg1 ;
-(NSDictionary *)upsightData;
-(unsigned long long)eventNumber;
-(void)setAttributeSetName:(NSString *)arg1 ;
-(void)setPubData:(NSDictionary *)arg1 ;
-(NSDictionary *)pubData;
-(id)initWithTimestamp:(double)arg1 eventType:(id)arg2 eventNumber:(unsigned long long)arg3 session:(id)arg4 attributeSetName:(id)arg5 userAttributes:(id)arg6 pubData:(id)arg7 upsightData:(id)arg8 ;
-(NSDictionary *)userAttributes;
-(NSString *)attributeSetName;
-(BOOL)isEqualToParameters:(id)arg1 ;
-(USSession *)session;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)init;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(double)timestamp;
-(void)setEventType:(NSString *)arg1 ;
-(NSString *)eventType;
@end

