/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UpsightDataStoreInterface;
@class NSMutableDictionary;

@interface USEventDataAssociationMap : NSObject {

	NSMutableDictionary* _typeToAssociationsMap;
	id<UpsightDataStoreInterface> _dataStore;
	double _expirationInterval;

}

@property (nonatomic,readonly) id<UpsightDataStoreInterface> dataStore;                  //@synthesize dataStore=_dataStore - In the implementation block
@property (nonatomic,readonly) NSMutableDictionary * typeToAssociationsMap;              //@synthesize typeToAssociationsMap=_typeToAssociationsMap - In the implementation block
@property (nonatomic,readonly) double expirationInterval;                                //@synthesize expirationInterval=_expirationInterval - In the implementation block
-(id)initWithDataStore:(id)arg1 expirationInterval:(double)arg2 ;
-(id)associationsForEventType:(id)arg1 ;
-(void)removeAssociation:(id)arg1 ;
-(void)addAssociation:(id)arg1 ;
-(NSMutableDictionary *)typeToAssociationsMap;
-(void)cacheStorables:(id)arg1 ;
-(void)removeCachedStorables:(id)arg1 ;
-(void)filterStorables:(id)arg1 expired:(id*)arg2 valid:(id*)arg3 ;
-(void)loadAndCacheAssociationStorables;
-(BOOL)isStorableExpired:(id)arg1 ;
-(id)init;
-(id<UpsightDataStoreInterface>)dataStore;
-(double)expirationInterval;
@end

