/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <pokemongo/pokemongo-Structs.h>
@interface USEventFactory : NSObject
+(id)analyticsEventWithName:(id)arg1 pubData:(id)arg2 ;
+(id)monetizationEventWithInfo:(id)arg1 pubData:(id)arg2 ;
+(id)inAppPurchaseEventWithIAPInfo:(id)arg1 pubData:(id)arg2 ;
+(id)milestoneEventForScope:(id)arg1 pubData:(id)arg2 ;
+(id)pushUnregistrationEventWithPubData:(id)arg1 ;
+(id)pushRegistrationEventWithToken:(id)arg1 pubData:(id)arg2 ;
+(id)unrenderedContentEventWithContentID:(id)arg1 campaignID:(id)arg2 scope:(id)arg3 pubData:(id)arg4 ;
+(id)pushReceivedEventWithMessageID:(id)arg1 campaignID:(id)arg2 pubData:(id)arg3 ;
+(id)configurationRequestWithPubData:(id)arg1 ;
+(id)dataCollectionEventWitDataBundle:(id)arg1 streamID:(id)arg2 pubData:(id)arg3 ;
+(id)dynamicEventWithEventDictionary:(id)arg1 ;
+(id)UXMEnumerateEventWithUXMSchema:(id)arg1 pubData:(id)arg2 ;
+(id)installEventWithPubData:(id)arg1 ;
+(id)sessionStartEventWithPubData:(id)arg1 ;
+(id)sessionPauseEventWithPubData:(id)arg1 ;
+(id)sessionResumeEventWithPubData:(id)arg1 ;
+(id)sharedFactory;
-(id)eventParametersWithAttributeSetName:(id)arg1 pubData:(id)arg2 ;
-(void)extendEventWithAssociatedData:(id)arg1 ;
-(id)buildEventWithInitializer:(/*^block*/id)arg1 attributeSetName:(id)arg2 pubData:(id)arg3 ;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

