/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface USManagedVariable : NSObject {

	NSString* _tag;
	id _value;

}

@property (nonatomic,retain) NSString * tag;              //@synthesize tag=_tag - In the implementation block
@property (nonatomic,retain) id value;                    //@synthesize value=_value - In the implementation block
+(id)managedIntegerWithTag:(id)arg1 ;
+(id)managedStringWithTag:(id)arg1 ;
+(id)managedFloatWithTag:(id)arg1 ;
+(id)managedBooleanWithTag:(id)arg1 ;
+(id)keyPathsForValuesAffectingValueForKey:(id)arg1 ;
-(id)init;
-(long long)integerValue;
-(BOOL)boolValue;
-(id)value;
-(void)setValue:(id)arg1 ;
-(float)floatValue;
-(NSString *)tag;
-(void)setTag:(NSString *)arg1 ;
-(id)stringValue;
-(id)initWithTag:(id)arg1 value:(id)arg2 ;
@end

