/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/pokemongo-Structs.h>
#import <pokemongo/USActionMapManagerObserver.h>
#import <pokemongo/USActionHandlerDelegate.h>
#import <pokemongo/USManagedVariableObserver.h>

@protocol USManagedVariableObserverDelegate, UpsightDataStoreInterface;
@class NSMutableDictionary, NSString, NSDictionary;

@interface USManagedVariableManager : NSObject <USActionMapManagerObserver, USActionHandlerDelegate, USManagedVariableObserver> {

	NSMutableDictionary* _tagsToManagedVariablesMap;
	NSMutableDictionary* _mapIDToTagsMap;
	NSString* _bundleHash;
	id<USManagedVariableObserverDelegate> _delegate;
	NSDictionary* _actionTypeToHandlerMap;
	NSMutableDictionary* _mapIDToSyncBool;
	id<UpsightDataStoreInterface> _dataStore;

}

@property (nonatomic,readonly) id<UpsightDataStoreInterface> dataStore;                          //@synthesize dataStore=_dataStore - In the implementation block
@property (readonly) NSMutableDictionary * tagsToManagedVariablesMap;                            //@synthesize tagsToManagedVariablesMap=_tagsToManagedVariablesMap - In the implementation block
@property (readonly) NSMutableDictionary * mapIDToTagsMap;                                       //@synthesize mapIDToTagsMap=_mapIDToTagsMap - In the implementation block
@property (readonly) NSMutableDictionary * mapIDToSyncBool;                                      //@synthesize mapIDToSyncBool=_mapIDToSyncBool - In the implementation block
@property (retain) NSString * bundleHash;                                                        //@synthesize bundleHash=_bundleHash - In the implementation block
@property (nonatomic,readonly) NSDictionary * actionTypeToHandlerMap;                            //@synthesize actionTypeToHandlerMap=_actionTypeToHandlerMap - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (assign,nonatomic,__weak) id<USManagedVariableObserverDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
+(id)managedVariableWithSchema:(id)arg1 ;
+(id)bundleHash;
+(id)bundleID;
+(id)sharedManager;
+(void)setBundleID:(id)arg1 ;
-(void)actionMapManager:(id)arg1 didDestroyActionMap:(id)arg2 ;
-(BOOL)shouldExecuteActionOfType:(id)arg1 fromMap:(id)arg2 ;
-(NSDictionary *)actionTypeToHandlerMap;
-(/*^block*/id)notifyUXMValuesSynchronized;
-(id)managedVariableWithSchema:(id)arg1 ;
-(NSString *)bundleHash;
-(void)onDidChangeUXMVariable:(id)arg1 action:(unsigned long long)arg2 ;
-(NSMutableDictionary *)tagsToManagedVariablesMap;
-(void)setBundleHash:(NSString *)arg1 ;
-(NSMutableDictionary *)mapIDToTagsMap;
-(NSMutableDictionary *)mapIDToSyncBool;
-(/*^block*/id)modifyValue;
-(/*^block*/id)UXMEnumerate;
-(/*^block*/id)setBundleID;
-(void)setDelegate:(id<USManagedVariableObserverDelegate>)arg1 ;
-(void)dealloc;
-(id)init;
-(id<USManagedVariableObserverDelegate>)delegate;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)initWithDataStore:(id)arg1 ;
-(id<UpsightDataStoreInterface>)dataStore;
@end

