/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSNumber;

@interface USMutableNumber : NSObject {

	NSNumber* _numberValue;

}

@property (assign,nonatomic) long long integerValue; 
@property (nonatomic,retain) NSNumber * numberValue;              //@synthesize numberValue=_numberValue - In the implementation block
-(void)setNumberValue:(NSNumber *)arg1 ;
-(id)init;
-(long long)integerValue;
-(id)initWithInteger:(unsigned long long)arg1 ;
-(NSNumber *)numberValue;
-(void)setIntegerValue:(long long)arg1 ;
@end

