/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSCoding.h>

@class NSString, NSDictionary;

@interface USPurchaseInfo : NSObject <NSCoding> {

	float _price;
	float _totalPrice;
	unsigned long long _resolution;
	NSString* _product;
	unsigned long long _quantity;
	NSString* _currency;

}

@property (assign,nonatomic) unsigned long long resolution;                          //@synthesize resolution=_resolution - In the implementation block
@property (nonatomic,retain) NSString * product;                                     //@synthesize product=_product - In the implementation block
@property (assign,nonatomic) unsigned long long quantity;                            //@synthesize quantity=_quantity - In the implementation block
@property (nonatomic,retain) NSString * currency;                                    //@synthesize currency=_currency - In the implementation block
@property (assign,nonatomic) float price;                                            //@synthesize price=_price - In the implementation block
@property (assign,nonatomic) float totalPrice;                                       //@synthesize totalPrice=_totalPrice - In the implementation block
@property (nonatomic,readonly) NSDictionary * dictionaryRepresentation; 
+(id)resolutionMap;
-(id)initWithResolution:(unsigned long long)arg1 totalPrice:(float)arg2 currency:(id)arg3 quantity:(unsigned long long)arg4 product:(id)arg5 price:(float)arg6 ;
-(float)totalPrice;
-(void)setTotalPrice:(float)arg1 ;
-(void)setProduct:(NSString *)arg1 ;
-(NSString *)product;
-(void)setQuantity:(unsigned long long)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)init;
-(BOOL)isEqual:(id)arg1 ;
-(NSDictionary *)dictionaryRepresentation;
-(id)initWithDictionaryRepresentation:(id)arg1 ;
-(unsigned long long)quantity;
-(NSString *)currency;
-(void)setCurrency:(NSString *)arg1 ;
-(unsigned long long)resolution;
-(void)setResolution:(unsigned long long)arg1 ;
-(float)price;
-(void)setPrice:(float)arg1 ;
@end

