/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray, USParametersProvider, NSMutableDictionary, NSDictionary;

@interface USRequestAttributeSetBuilder : NSObject {

	NSArray* _attributeSets;
	NSArray* _attributeSetFilters;
	USParametersProvider* _parameterProvider;
	NSMutableDictionary* _modifiedFiltersToOriginals;
	NSMutableDictionary* _filtersToAttributeSetNames;
	NSDictionary* _baseParameterToSelectorMap;
	NSDictionary* _optionalParameterToSelectorMap;
	NSMutableDictionary* _parameterProvidersCache;

}

@property (nonatomic,retain) NSArray * attributeSets;                                       //@synthesize attributeSets=_attributeSets - In the implementation block
@property (nonatomic,retain) NSArray * attributeSetFilters;                                 //@synthesize attributeSetFilters=_attributeSetFilters - In the implementation block
@property (nonatomic,retain) USParametersProvider * parameterProvider;                      //@synthesize parameterProvider=_parameterProvider - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * modifiedFiltersToOriginals;              //@synthesize modifiedFiltersToOriginals=_modifiedFiltersToOriginals - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * filtersToAttributeSetNames;              //@synthesize filtersToAttributeSetNames=_filtersToAttributeSetNames - In the implementation block
@property (nonatomic,retain) NSDictionary * baseParameterToSelectorMap;                     //@synthesize baseParameterToSelectorMap=_baseParameterToSelectorMap - In the implementation block
@property (nonatomic,retain) NSDictionary * optionalParameterToSelectorMap;                 //@synthesize optionalParameterToSelectorMap=_optionalParameterToSelectorMap - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * parameterProvidersCache;                 //@synthesize parameterProvidersCache=_parameterProvidersCache - In the implementation block
-(id)attributeSetNameForEvent:(id)arg1 ;
-(id)parametersForAttributeSetNamed:(id)arg1 ;
-(id)initWithAttributeSets:(id)arg1 attributeSetFilters:(id)arg2 parameterProvider:(id)arg3 ;
-(NSMutableDictionary *)modifiedFiltersToOriginals;
-(NSMutableDictionary *)filtersToAttributeSetNames;
-(NSMutableDictionary *)parameterProvidersCache;
-(id)excludesForAttributeSetWithName:(id)arg1 ;
-(id)includesForAttributeSetWithName:(id)arg1 ;
-(NSDictionary *)baseParameterToSelectorMap;
-(id)excludeAttributes:(id)arg1 fromSet:(id)arg2 ;
-(id)includeAttributes:(id)arg1 inSet:(id)arg2 ;
-(id)parametersFromProviders:(id)arg1 ;
-(NSDictionary *)optionalParameterToSelectorMap;
-(USParametersProvider *)parameterProvider;
-(void)setAttributeSets:(NSArray *)arg1 ;
-(NSArray *)attributeSetFilters;
-(void)setAttributeSetFilters:(NSArray *)arg1 ;
-(void)setParameterProvider:(USParametersProvider *)arg1 ;
-(void)setModifiedFiltersToOriginals:(NSMutableDictionary *)arg1 ;
-(void)setFiltersToAttributeSetNames:(NSMutableDictionary *)arg1 ;
-(void)setBaseParameterToSelectorMap:(NSDictionary *)arg1 ;
-(void)setOptionalParameterToSelectorMap:(NSDictionary *)arg1 ;
-(void)setParameterProvidersCache:(NSMutableDictionary *)arg1 ;
-(id)init;
-(NSArray *)attributeSets;
@end

