/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableSet, USInstallationTracker;

@interface USServiceManager : NSObject {

	BOOL _initialized;
	NSMutableSet* _services;
	USInstallationTracker* _installationTracker;

}

@property (assign,nonatomic) BOOL initialized;                                         //@synthesize initialized=_initialized - In the implementation block
@property (nonatomic,retain) NSMutableSet * services;                                  //@synthesize services=_services - In the implementation block
@property (nonatomic,retain) USInstallationTracker * installationTracker;              //@synthesize installationTracker=_installationTracker - In the implementation block
+(id)analyticsForStore:(id)arg1 ;
+(id)billboardManagerForStore:(id)arg1 ;
+(id)actionMapManagerForStore:(id)arg1 ;
+(id)installationTracker;
+(void)load;
+(id)sharedServiceManager;
-(id)analyticsForStore:(id)arg1 ;
-(id)billboardManagerForStore:(id)arg1 ;
-(id)actionMapManagerForStore:(id)arg1 ;
-(void)installObservers;
-(id)servicesForDataStore:(id)arg1 ;
-(void)startServicesWithStore:(id)arg1 ;
-(USInstallationTracker *)installationTracker;
-(void)onApplicationDidFinishLaunching:(id)arg1 ;
-(void)initializeSDK;
-(void)setInstallationTracker:(USInstallationTracker *)arg1 ;
-(void)stopServicesWithStore:(id)arg1 ;
-(id)dispatcherForStore:(id)arg1 ;
-(id)configurationManagerForStore:(id)arg1 ;
-(void)dealloc;
-(id)init;
-(void)setInitialized:(BOOL)arg1 ;
-(BOOL)initialized;
-(NSMutableSet *)services;
-(void)setServices:(NSMutableSet *)arg1 ;
@end

