/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface USStateDefinition : NSObject {

	/*^block*/id _enterBlock;
	/*^block*/id _executeBlock;
	/*^block*/id _exitBlock;

}

@property (nonatomic,copy) id enterBlock;                //@synthesize enterBlock=_enterBlock - In the implementation block
@property (nonatomic,copy) id executeBlock;              //@synthesize executeBlock=_executeBlock - In the implementation block
@property (nonatomic,copy) id exitBlock;                 //@synthesize exitBlock=_exitBlock - In the implementation block
-(id)enterBlock;
-(void)setEnterBlock:(id)arg1 ;
-(void)setExecuteBlock:(id)arg1 ;
-(id)exitBlock;
-(void)setExitBlock:(id)arg1 ;
-(id)executeBlock;
@end

