/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/USDeliveryQueueInterface.h>

@protocol USDeliveryQueueDelegate;
@class USQueueConfiguration, NSString, NSOperationQueue;

@interface USTrashDeliveryQueue : NSObject <USDeliveryQueueInterface> {

	id<USDeliveryQueueDelegate> _delegate;
	USQueueConfiguration* _queueConfiguration;
	NSOperationQueue* _operationQueue;

}

@property (nonatomic,retain) USQueueConfiguration * queueConfiguration;                //@synthesize queueConfiguration=_queueConfiguration - In the implementation block
@property (nonatomic,retain) NSOperationQueue * operationQueue;                        //@synthesize operationQueue=_operationQueue - In the implementation block
@property (nonatomic,readonly) NSString * name; 
@property (assign,nonatomic,__weak) id<USDeliveryQueueDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(id)initWithQueueConfiguration:(id)arg1 operationQueue:(id)arg2 ;
-(USQueueConfiguration *)queueConfiguration;
-(void)enqueuePacket:(id)arg1 ;
-(void)setQueueConfiguration:(USQueueConfiguration *)arg1 ;
-(void)setDelegate:(id<USDeliveryQueueDelegate>)arg1 ;
-(id)init;
-(id<USDeliveryQueueDelegate>)delegate;
-(NSString *)name;
-(void)setOperationQueue:(NSOperationQueue *)arg1 ;
-(void)drain;
-(NSOperationQueue *)operationQueue;
@end

