/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <pokemongo/USEvent.h>

@class NSNumber, NSString;

@interface USUnrenderedContentEvent : USEvent

@property (nonatomic,readonly) NSNumber * contentID; 
@property (nonatomic,readonly) NSNumber * campaignID; 
@property (nonatomic,readonly) NSString * scope; 
+(id)eventWithParameters:(id)arg1 contentID:(id)arg2 campaignID:(id)arg3 scope:(id)arg4 ;
-(id)initWithType:(id)arg1 parameters:(id)arg2 ;
-(NSNumber *)campaignID;
-(id)initWithParameters:(id)arg1 contentID:(id)arg2 campaignID:(id)arg3 scope:(id)arg4 ;
-(NSNumber *)contentID;
-(NSString *)scope;
@end

