/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSURLConnection, NSURL;

@interface USURLLoaderItem : NSObject {

	NSURLConnection* _connection;
	NSURL* _resultingURL;
	unsigned long long _numberOfRedirects;

}

@property (nonatomic,retain) NSURLConnection * connection;                      //@synthesize connection=_connection - In the implementation block
@property (nonatomic,retain) NSURL * resultingURL;                              //@synthesize resultingURL=_resultingURL - In the implementation block
@property (assign,nonatomic) unsigned long long numberOfRedirects;              //@synthesize numberOfRedirects=_numberOfRedirects - In the implementation block
-(NSURL *)resultingURL;
-(void)setResultingURL:(NSURL *)arg1 ;
-(unsigned long long)numberOfRedirects;
-(void)setNumberOfRedirects:(unsigned long long)arg1 ;
-(NSURLConnection *)connection;
-(void)setConnection:(NSURLConnection *)arg1 ;
@end

