/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:59 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UpsightDataStoreInterface, USActionHandlerDelegate;
@interface USUXMModifyValueActionHandler : NSObject {

	id<UpsightDataStoreInterface> _dataStore;
	id<USActionHandlerDelegate> _delegate;

}

@property (nonatomic,readonly) id<UpsightDataStoreInterface> dataStore;                //@synthesize dataStore=_dataStore - In the implementation block
@property (nonatomic,readonly) id modifyValueActionHandler; 
@property (assign,nonatomic,__weak) id<USActionHandlerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
-(id)modifyValueActionHandler;
-(void)setDelegate:(id<USActionHandlerDelegate>)arg1 ;
-(id<USActionHandlerDelegate>)delegate;
-(id)initWithDataStore:(id)arg1 ;
-(id<UpsightDataStoreInterface>)dataStore;
@end

