/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, July 13, 2016 at 11:49:58 AM Central European Summer Time
* Operating System: Version 9.0.2 (Build 13A452)
* Image Source: /var/mobile/Containers/Bundle/Application/12E1CB67-3672-460D-A66D-1980A9BFC6C0/pokemongo.app/pokemongo
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol VideoPlayerDelegate;
#import <pokemongo/pokemongo-Structs.h>
@class AVPlayerItem, AVPlayer, AVAssetReader, AVAssetReaderTrackOutput;

@interface VideoPlayer : NSObject {

	id<VideoPlayerDelegate> delegate;
	AVPlayerItem* _playerItem;
	AVPlayer* _player;
	AVAssetReader* _reader;
	AVAssetReaderTrackOutput* _videoOut;
	opaqueCMSampleBufferRef _cmSampleBuffer;
	CMVideoSampling* _videoSampling;
	SCD_Struct_Vi6 _duration;
	SCD_Struct_Vi6 _curTime;
	SCD_Struct_Vi6 _curFrameTimestamp;
	SCD_Struct_Vi6 _lastFrameTimestamp;
	CGSize _videoSize;
	BOOL _playerReady;
	BOOL _assetReady;
	BOOL _itemReady;

}

@property (nonatomic,retain) id delegate; 
@property (nonatomic,readonly) AVPlayer * player;              //@synthesize player=_player - In the implementation block
+(BOOL)CheckScalingModeAspectFill:(CGSize)arg1 screenSize:(CGSize)arg2 ;
+(BOOL)CanPlayToTexture:(id)arg1 ;
-(void)audioRouteChanged:(id)arg1 ;
-(BOOL)loadVideo:(id)arg1 ;
-(BOOL)playVideoPlayer;
-(void)unloadPlayer;
-(void)cleanupCVTextureCache;
-(void)cleanupAssetReader;
-(void)cleanupPlayer;
-(void)prepareAsset:(id)arg1 withKeys:(id)arg2 ;
-(BOOL)_playWithPrepareBlock:(/*^block*/id)arg1 ;
-(BOOL)prepareReader;
-(void)seekToTimestamp:(SCD_Struct_Vi6)arg1 ;
-(void)reportError:(id)arg1 category:(const char*)arg2 ;
-(void)reportErrorWithString:(const char*)arg1 category:(const char*)arg2 ;
-(BOOL)readyToPlay;
-(float)durationSeconds;
-(BOOL)playToView:(id)arg1 ;
-(BOOL)playToTexture;
-(long long)curFrameTexture;
-(void)seekTo:(float)arg1 ;
-(CGSize)videoSize;
-(BOOL)isPlaying;
-(AVPlayer *)player;
-(void)setDelegate:(id)arg1 ;
-(id)init;
-(id)delegate;
-(SCD_Struct_Vi6)duration;
-(void)resume;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4 ;
-(void)pause;
-(void)playerItemDidReachEnd:(id)arg1 ;
-(BOOL)setAudioVolume:(float)arg1 ;
-(void)rewind;
@end

